// SPDX-License-Identifier: GPL-2.0
//
// Power sequences of the Google Zumapro (Tensor G4) power domains.
//
// Copyright (c) 2026 Steffen Deusch
//
// Transcribed from the vendor kernel's pmucal tables for this SoC: for every
// domain a CONFIGURATION write followed by a STATUS poll, the CMU controller
// option written before the domain goes down, and for the GPU pair the PLL,
// mux and Q-channel handling around the transition.  The register names in
// the comments are the vendor's.

#include "exynos-pm-domains.h"

/* The domain's block in the PMU */
#define PD_CONFIGURATION		0x0
#define PD_STATUS			0x4
#define PD_OUT				0x20
#define PD_LOCAL_PWR_CFG		BIT(0)

/* Every CMU */
#define CMU_CONTROLLER_OPTION		0x800
/*
 * Cleared before every power-down in the vendor tables; the clock driver
 * carries the same bit as the memory power-gating enable.
 */
#define CMU_OPT_EN_MEM_PWR_GATING	BIT(24)

/* PLL_CONx and PLL_CON0_MUX_*_USER */
#define PLL_CON0_MUX_SEL		BIT(4)
#define PLL_CON_ENABLE			BIT(31)
#define PLL_CON_LOCKED			BIT(29)

/* QCH_CON_* */
#define QCH_CON_ENABLE			BIT(0)
#define QCH_CON_CLOCK_REQ		BIT(1)
#define QCH_CON_IGNORE_FORCE_PM_EN	BIT(2)
#define QCH_CON_MODE_MASK		GENMASK(2, 0)

/*
 * What every domain does: CONFIGURATION up and wait for STATUS to follow,
 * and the controller option of the domain's CMU down before CONFIGURATION.
 */
static const struct exynos_pd_step zumapro_pd_on[] = {
	PD_WRITE(PMU, PD_CONFIGURATION, PD_LOCAL_PWR_CFG, PD_LOCAL_PWR_CFG),
	PD_WAIT(PMU, PD_STATUS, PD_LOCAL_PWR_CFG, PD_LOCAL_PWR_CFG),
};

static const struct exynos_pd_step zumapro_pd_off[] = {
	PD_WRITE(CMU, CMU_CONTROLLER_OPTION, CMU_OPT_EN_MEM_PWR_GATING, 0),
	PD_WRITE(PMU, PD_CONFIGURATION, PD_LOCAL_PWR_CFG, 0),
	PD_WAIT(PMU, PD_STATUS, PD_LOCAL_PWR_CFG, 0),
};

/*
 * Every domain carries the vendor's save list, whether or not its CMU has a
 * clock provider: the provider restores what it saved itself (its gates
 * among them) from its genpd notifier, after the on sequence has restored
 * the list below.
 */

/*
 * G3D, the GPU's top level.  Nothing else drives CMU_G3D, so the domain
 * carries the vendor's save list for it: the two PLLs, the dividers and
 * muxes, the Q-channels, the controller options, the clock-divider step
 * and short-stop settings, and the SYSREG_G3D clock gating words.  The
 * restore also switches the G3DCORE muxes to their PLL side and waits for a
 * PLL that is enabled to lock, in the vendor's order.
 */
static const struct exynos_pd_step zumapro_g3d_save[] = {
	PD_SAVE(CMU, 0x0000),	/* PLL_LOCKTIME_PLL_G3D */
	PD_SAVE(CMU, 0x0008),	/* PLL_LOCKTIME_PLL_G3D_L2 */
	PD_SAVE(CMU, 0x0080),	/* PLL_LOCKTIME_REG_PLL_G3D */
	PD_SAVE(CMU, 0x0084),	/* PLL_LOCKTIME_REG_PLL_G3D_L2 */
	PD_SAVE(CMU, 0x0108),	/* PLL_CON2_PLL_G3D */
	PD_SAVE(CMU, 0x0110),	/* PLL_CON4_PLL_G3D */
	PD_SAVE(CMU, 0x0114),	/* PLL_CON5_PLL_G3D */
	PD_SAVE(CMU, 0x011c),	/* PLL_CON7_PLL_G3D */
	PD_SAVE(CMU, 0x0120),	/* PLL_CON8_PLL_G3D */
	PD_SAVE(CMU, 0x0188),	/* PLL_CON2_PLL_G3D_L2 */
	PD_SAVE(CMU, 0x0190),	/* PLL_CON4_PLL_G3D_L2 */
	PD_SAVE(CMU, 0x0194),	/* PLL_CON5_PLL_G3D_L2 */
	PD_SAVE(CMU, 0x019c),	/* PLL_CON7_PLL_G3D_L2 */
	PD_SAVE(CMU, 0x01a0),	/* PLL_CON8_PLL_G3D_L2 */
	PD_SAVE(CMU, 0x0118),	/* PLL_CON6_PLL_G3D */
	PD_SAVE(CMU, 0x0198),	/* PLL_CON6_PLL_G3D_L2 */
	PD_SAVE(CMU, 0x1800),	/* CLK_CON_DIV_CLK_G3D_ADD_CH_CLK */
	PD_SAVE(CMU, 0x1804),	/* CLK_CON_DIV_DIV_CLK_G3D_L2_GLB */
	PD_SAVE(CMU, 0x1808),	/* CLK_CON_DIV_DIV_CLK_G3D_NOCP */
	PD_SAVE(CMU, 0x180c),	/* CLK_CON_DIV_DIV_CLK_G3D_NOCP_LH */
	PD_SAVE(CMU, 0x1810),	/* CLK_CON_DIV_DIV_CLK_G3D_STACKS */
	PD_SAVE(CMU, 0x1814),	/* CLK_CON_DIV_DIV_CLK_G3D_TOP */
	PD_SAVE(CMU, 0x1000),	/* CLK_CON_MUX_MUX_CLK_G3D_L2_GLB */
	PD_SAVE(CMU, 0x1004),	/* CLK_CON_MUX_MUX_CLK_G3D_STACKS */
	PD_SAVE(CMU, 0x1008),	/* CLK_CON_MUX_MUX_CLK_G3D_TOP */
	PD_SAVE(CMU, 0x0600),	/* PLL_CON0_MUX_CLKCMU_G3D_GLB_USER */
	PD_SAVE(CMU, 0x0610),	/* PLL_CON0_MUX_CLKCMU_G3D_NOCD_USER */
	PD_SAVE(CMU, 0x0620),	/* PLL_CON0_MUX_CLKCMU_G3D_SWITCH_USER */
	/* PLL_CON0_MUX_CLK_G3DCORE_{COREGROUP,STACKS,TOP,TRACE}_USER */
	PD_WRITE(CMU, 0x0630, PLL_CON0_MUX_SEL, PLL_CON0_MUX_SEL),
	PD_WRITE(CMU, 0x0640, PLL_CON0_MUX_SEL, PLL_CON0_MUX_SEL),
	PD_WRITE(CMU, 0x0650, PLL_CON0_MUX_SEL, PLL_CON0_MUX_SEL),
	PD_WRITE(CMU, 0x0660, PLL_CON0_MUX_SEL, PLL_CON0_MUX_SEL),
	/* PLL_CON6_PLL_G3D, PLL_CON6_PLL_G3D_L2: wait for lock if enabled */
	PD_SKIP_IF(CMU, 0x0118, PLL_CON_ENABLE, 0),
	PD_WAIT(CMU, 0x0118, PLL_CON_LOCKED, PLL_CON_LOCKED),
	PD_SKIP_IF(CMU, 0x0198, PLL_CON_ENABLE, 0),
	PD_WAIT(CMU, 0x0198, PLL_CON_LOCKED, PLL_CON_LOCKED),
	PD_SAVE(CMU, 0x010c),	/* PLL_CON3_PLL_G3D */
	PD_SAVE(CMU, 0x018c),	/* PLL_CON3_PLL_G3D_L2 */
	/* PLL_CON3_PLL_G3D, PLL_CON3_PLL_G3D_L2: wait for lock if enabled */
	PD_SKIP_IF(CMU, 0x010c, PLL_CON_ENABLE, 0),
	PD_WAIT(CMU, 0x010c, PLL_CON_LOCKED, PLL_CON_LOCKED),
	PD_SKIP_IF(CMU, 0x018c, PLL_CON_ENABLE, 0),
	PD_WAIT(CMU, 0x018c, PLL_CON_LOCKED, PLL_CON_LOCKED),
	PD_SAVE(CMU, 0x0100),	/* PLL_CON0_PLL_G3D */
	PD_SAVE(CMU, 0x0104),	/* PLL_CON1_PLL_G3D */
	PD_SAVE(CMU, 0x0180),	/* PLL_CON0_PLL_G3D_L2 */
	PD_SAVE(CMU, 0x0184),	/* PLL_CON1_PLL_G3D_L2 */
	PD_SAVE(CMU, 0x3000),	/* DMYQCH_CON_ADD_G3D_QCH */
	PD_SAVE(CMU, 0x3004),	/* DMYQCH_CON_ADM_DAP_G_GPU_QCH */
	PD_SAVE(CMU, 0x3034),	/* QCH_CON_ADD_APBIF_G3D_QCH */
	PD_SAVE(CMU, 0x3038),	/* QCH_CON_D_TZPC_G3D_QCH */
	PD_SAVE(CMU, 0x303c),	/* QCH_CON_G3D_CMU_G3D_QCH */
	PD_SAVE(CMU, 0x3040),	/* QCH_CON_GPC_G3D_QCH */
	PD_SAVE(CMU, 0x3044),	/* QCH_CON_GPU_QCH */
	PD_SAVE(CMU, 0x3048),	/* QCH_CON_LH_ACEL_SI_D0_G3D_QCH */
	PD_SAVE(CMU, 0x304c),	/* QCH_CON_LH_ACEL_SI_D1_G3D_QCH */
	PD_SAVE(CMU, 0x3050),	/* QCH_CON_LH_ACEL_SI_D2_G3D_QCH */
	PD_SAVE(CMU, 0x3054),	/* QCH_CON_LH_ACEL_SI_D3_G3D_QCH */
	PD_SAVE(CMU, 0x3058),	/* QCH_CON_LH_ATB_SI_LT_G3D_CPUCL0_QCH */
	PD_SAVE(CMU, 0x305c),	/* QCH_CON_LH_AXI_MI_IP_G3D_QCH */
	PD_SAVE(CMU, 0x3060),	/* QCH_CON_LH_AXI_MI_P_G3D_CU_QCH */
	PD_SAVE(CMU, 0x3064),	/* QCH_CON_LH_AXI_SI_IP_G3D_QCH */
	PD_SAVE(CMU, 0x3068),	/* QCH_CON_LH_AXI_SI_P_G3D_CU_QCH */
	PD_SAVE(CMU, 0x306c),	/* QCH_CON_PPCFW_G3D0_QCH */
	PD_SAVE(CMU, 0x3070),	/* QCH_CON_PPCFW_G3D1_QCH */
	PD_SAVE(CMU, 0x3074),	/* QCH_CON_PPMU_G3D_D0_QCH */
	PD_SAVE(CMU, 0x3078),	/* QCH_CON_PPMU_G3D_D1_QCH */
	PD_SAVE(CMU, 0x307c),	/* QCH_CON_PPMU_G3D_D2_QCH */
	PD_SAVE(CMU, 0x3080),	/* QCH_CON_PPMU_G3D_D3_QCH */
	PD_SAVE(CMU, 0x3084),	/* QCH_CON_RSTNSYNC_CLK_G3D_DD_QCH */
	PD_SAVE(CMU, 0x3088),	/* QCH_CON_SLH_AXI_MI_P_G3D_QCH */
	PD_SAVE(CMU, 0x308c),	/* QCH_CON_SLH_AXI_SI_D_G3DMMU_QCH */
	PD_SAVE(CMU, 0x3090),	/* QCH_CON_SSMT_G3D0_QCH */
	PD_SAVE(CMU, 0x3094),	/* QCH_CON_SSMT_G3D1_QCH */
	PD_SAVE(CMU, 0x3098),	/* QCH_CON_SSMT_G3D2_QCH */
	PD_SAVE(CMU, 0x309c),	/* QCH_CON_SSMT_G3D3_QCH */
	PD_SAVE(CMU, 0x30a0),	/* QCH_CON_SYSMMU_S0_G3D_QCH_S0 */
	PD_SAVE(CMU, 0x30a4),	/* QCH_CON_SYSMMU_S0_PMMU0_G3D_QCH_S0 */
	PD_SAVE(CMU, 0x30a8),	/* QCH_CON_SYSMMU_S0_PMMU1_G3D_QCH_S0 */
	PD_SAVE(CMU, 0x30ac),	/* QCH_CON_SYSMMU_S0_PMMU2_G3D_QCH_S0 */
	PD_SAVE(CMU, 0x30b0),	/* QCH_CON_SYSMMU_S0_PMMU3_G3D_QCH_S0 */
	PD_SAVE(CMU, 0x30b4),	/* QCH_CON_SYSREG_G3D_QCH */
	PD_SAVE(CMU, 0x30b8),	/* QCH_CON_UASC_G3D_QCH */
	PD_SAVE(CMU, 0x0800),	/* G3D_CMU_G3D_CONTROLLER_OPTION */
	PD_SAVE(CMU, 0x0804),	/* G3D_EMBEDDED_CMU_G3D_CONTROLLER_OPTION */
	PD_SAVE(CMU, 0x0840),	/* G3D_CLKDIVSTEP_CON_HEAVY */
	PD_SAVE(CMU, 0x0844),	/* G3D_CLKDIVSTEP_CON_LIGHT */
	PD_SAVE(CMU, 0x0834),	/* G3D_CLKDIVSTEP_OCP_FLT */
	PD_SAVE(CMU, 0x0838),	/* G3D_CLKDIVSTEP_VDROOP_FLT */
	PD_SAVE(CMU, 0x083c),	/* G3D_CLKDIVSTEP_SMPL_FLT */
	PD_SAVE(CMU, 0x0830),	/* G3D_CLKDIVSTEP */
	PD_SAVE(CMU, 0x0820),	/* G3D_SHORTSTOP */
	PD_SAVE(SYSREG, 0x0104),	/* BUS_COMPONENT_DRCG_EN */
	PD_SAVE(SYSREG, 0x0108),	/* MEMCLK */
};

/*
 * EMBEDDED_G3D, the shader cores, a child of G3D.  Coming up, both PLLs are
 * put back into their running configuration and the G3DCORE muxes switched
 * to them, EMBEDDED_G3D_OUT bit 1 is set through the PMU's set-bit alias
 * and given 280 us before the domain is configured on.  Going down, the GPU
 * Q-channel is told to ignore forced power management while the domain
 * goes off, then returned to a plain clock request, the muxes are switched
 * away from the PLLs and the PLLs parked.
 */
static const struct exynos_pd_step zumapro_g3d_cores_on[] = {
	PD_WRITE(CMU, 0x0104, U32_MAX, 0x38000003),	/* PLL_CON1_PLL_G3D */
	PD_WRITE(CMU, 0x0100, PLL_CON0_MUX_SEL, PLL_CON0_MUX_SEL),	/* PLL_CON0_PLL_G3D */
	PD_WRITE(CMU, 0x0184, U32_MAX, 0x38000003),	/* PLL_CON1_PLL_G3D_L2 */
	PD_WRITE(CMU, 0x0180, PLL_CON0_MUX_SEL, PLL_CON0_MUX_SEL),	/* PLL_CON0_PLL_G3D_L2 */
	/* PLL_CON0_MUX_CLK_G3DCORE_{COREGROUP,STACKS,TOP,TRACE}_USER */
	PD_WRITE(CMU, 0x0630, PLL_CON0_MUX_SEL, PLL_CON0_MUX_SEL),
	PD_WRITE(CMU, 0x0640, PLL_CON0_MUX_SEL, PLL_CON0_MUX_SEL),
	PD_WRITE(CMU, 0x0650, PLL_CON0_MUX_SEL, PLL_CON0_MUX_SEL),
	PD_WRITE(CMU, 0x0660, PLL_CON0_MUX_SEL, PLL_CON0_MUX_SEL),
	PD_SET_BITS(PD_OUT, BIT(1)),			/* EMBEDDED_G3D_OUT */
	PD_DELAY_US(280),
	PD_WRITE(PMU, PD_CONFIGURATION, PD_LOCAL_PWR_CFG, PD_LOCAL_PWR_CFG),
	PD_WAIT(PMU, PD_STATUS, PD_LOCAL_PWR_CFG, PD_LOCAL_PWR_CFG),
};

static const struct exynos_pd_step zumapro_g3d_cores_off[] = {
	PD_WRITE(CMU, 0x3044, QCH_CON_MODE_MASK,	/* QCH_CON_GPU_QCH */
		 QCH_CON_CLOCK_REQ | QCH_CON_IGNORE_FORCE_PM_EN),
	PD_WRITE(PMU, PD_CONFIGURATION, PD_LOCAL_PWR_CFG, 0),
	PD_WAIT(PMU, PD_STATUS, PD_LOCAL_PWR_CFG, 0),
	PD_WRITE(CMU, 0x3044, QCH_CON_MODE_MASK, QCH_CON_CLOCK_REQ),
	/* PLL_CON0_MUX_CLK_G3DCORE_{COREGROUP,STACKS,TOP,TRACE}_USER */
	PD_WRITE(CMU, 0x0630, PLL_CON0_MUX_SEL, 0),
	PD_WRITE(CMU, 0x0640, PLL_CON0_MUX_SEL, 0),
	PD_WRITE(CMU, 0x0650, PLL_CON0_MUX_SEL, 0),
	PD_WRITE(CMU, 0x0660, PLL_CON0_MUX_SEL, 0),
	PD_WRITE(CMU, 0x0100, PLL_CON0_MUX_SEL, 0),	/* PLL_CON0_PLL_G3D */
	PD_WRITE(CMU, 0x0104, U32_MAX, 0x18000001),	/* PLL_CON1_PLL_G3D */
	PD_WRITE(CMU, 0x0180, PLL_CON0_MUX_SEL, 0),	/* PLL_CON0_PLL_G3D_L2 */
	PD_WRITE(CMU, 0x0184, U32_MAX, 0x18000001),	/* PLL_CON1_PLL_G3D_L2 */
};

/*
 * The domains whose CMU has a clock provider.  The provider saves its own
 * registers (its gates among them) at its runtime suspend and writes them
 * back from its genpd notifier after the domain is on; the vendor's list
 * below is restored by the on sequence before that, and the two overlap
 * on identical values.  What only the list carries: the controller option,
 * the Q-channels, HSI1's dividers and mux, and the SYSREG DRCG and MEMCLK
 * words of every block, which sit outside the CMU.
 */
/* DPUB */
static const struct exynos_pd_step zumapro_dpub_save[] = {
	PD_SAVE(CMU, 0x1800),	/* CLK_CON_DIV_DIV_CLK_DPUB_NOCP */
	PD_SAVE(CMU, 0x0600),	/* PLL_CON0_MUX_CLKCMU_DPUB_DSIM_USER */
	PD_SAVE(CMU, 0x0610),	/* PLL_CON0_MUX_CLKCMU_DPUB_NOC_USER */
	PD_SAVE(CMU, 0x3060),	/* QCH_CON_DPUB_CMU_DPUB_QCH */
	PD_SAVE(CMU, 0x3064),	/* QCH_CON_DPUB_QCH */
	PD_SAVE(CMU, 0x3068),	/* QCH_CON_DPUB_QCH_ALV_DSIM0 */
	PD_SAVE(CMU, 0x306c),	/* QCH_CON_DPUB_QCH_ALV_DSIM1 */
	PD_SAVE(CMU, 0x3070),	/* QCH_CON_DPUB_QCH_OSC_DSIM0 */
	PD_SAVE(CMU, 0x3074),	/* QCH_CON_DPUB_QCH_OSC_DSIM1 */
	PD_SAVE(CMU, 0x3078),	/* QCH_CON_D_TZPC_DPUB_QCH */
	PD_SAVE(CMU, 0x307c),	/* QCH_CON_GPC_DPUB_QCH */
	PD_SAVE(CMU, 0x30ec),	/* QCH_CON_SLH_AXI_MI_P_DPUB_QCH */
	PD_SAVE(CMU, 0x30f0),	/* QCH_CON_SYSREG_DPUB_QCH */
	PD_SAVE(CMU, 0x0800),	/* DPUB_CMU_DPUB_CONTROLLER_OPTION */
	PD_SAVE(SYSREG, 0x0104),	/* BUS_COMPONENT_DRCG_EN */
	PD_SAVE(SYSREG, 0x0108),	/* MEMCLK */
};

/* DPUF0 */
static const struct exynos_pd_step zumapro_dpuf0_save[] = {
	PD_SAVE(CMU, 0x1800),	/* CLK_CON_DIV_DIV_CLK_DPUF0_NOCP */
	PD_SAVE(CMU, 0x0600),	/* PLL_CON0_MUX_CLKCMU_DPUF0_NOC_USER */
	PD_SAVE(CMU, 0x3044),	/* QCH_CON_DPUF0_CMU_DPUF0_QCH */
	PD_SAVE(CMU, 0x3048),	/* QCH_CON_DPUF0_QCH_DPUF */
	PD_SAVE(CMU, 0x304c),	/* QCH_CON_DPUF0_QCH_SRAMC */
	PD_SAVE(CMU, 0x3054),	/* QCH_CON_D_TZPC_DPUF0_QCH */
	PD_SAVE(CMU, 0x3058),	/* QCH_CON_GPC_DPUF0_QCH */
	PD_SAVE(CMU, 0x308c),	/* QCH_CON_LH_AXI_MI_LD0_DPUF1_DPUF0_QCH */
	PD_SAVE(CMU, 0x3090),	/* QCH_CON_LH_AXI_MI_LD1_DPUF1_DPUF0_QCH */
	PD_SAVE(CMU, 0x3094),	/* QCH_CON_LH_AXI_SI_D0_DPUF0_QCH */
	PD_SAVE(CMU, 0x3098),	/* QCH_CON_LH_AXI_SI_D1_DPUF0_QCH */
	PD_SAVE(CMU, 0x309c),	/* QCH_CON_PPMU_D0_DPUF0_QCH */
	PD_SAVE(CMU, 0x30a0),	/* QCH_CON_PPMU_D1_DPUF0_QCH */
	PD_SAVE(CMU, 0x30a4),	/* QCH_CON_SLH_AXI_MI_P_DPUF0_QCH */
	PD_SAVE(CMU, 0x30a8),	/* QCH_CON_SSMT_D0_DPUF0_QCH */
	PD_SAVE(CMU, 0x30ac),	/* QCH_CON_SSMT_D1_DPUF0_QCH */
	PD_SAVE(CMU, 0x30b0),	/* QCH_CON_SYSMMU_S0_DPUF0_QCH_S0 */
	PD_SAVE(CMU, 0x30b4),	/* QCH_CON_SYSMMU_S0_PMMU0_DPUF0_QCH_S0 */
	PD_SAVE(CMU, 0x30b8),	/* QCH_CON_SYSMMU_S0_PMMU1_DPUF0_QCH_S0 */
	PD_SAVE(CMU, 0x30bc),	/* QCH_CON_SYSREG_DPUF0_QCH */
	PD_SAVE(CMU, 0x0800),	/* DPUF0_CMU_DPUF0_CONTROLLER_OPTION */
	PD_SAVE(SYSREG, 0x0104),	/* BUS_COMPONENT_DRCG_EN */
	PD_SAVE(SYSREG, 0x0108),	/* MEMCLK */
};

/* DPUF1 */
static const struct exynos_pd_step zumapro_dpuf1_save[] = {
	PD_SAVE(CMU, 0x1800),	/* CLK_CON_DIV_DIV_CLK_DPUF1_NOCP */
	PD_SAVE(CMU, 0x0600),	/* PLL_CON0_MUX_CLKCMU_DPUF1_NOC_USER */
	PD_SAVE(CMU, 0x303c),	/* QCH_CON_DPUF1_CMU_DPUF1_QCH */
	PD_SAVE(CMU, 0x3040),	/* QCH_CON_DPUF1_QCH_DPUF */
	PD_SAVE(CMU, 0x3044),	/* QCH_CON_DPUF1_QCH_SRAMC */
	PD_SAVE(CMU, 0x304c),	/* QCH_CON_D_TZPC_DPUF1_QCH */
	PD_SAVE(CMU, 0x3050),	/* QCH_CON_GPC_DPUF1_QCH */
	PD_SAVE(CMU, 0x3084),	/* QCH_CON_LH_AXI_SI_LD0_DPUF1_DPUF0_QCH */
	PD_SAVE(CMU, 0x3088),	/* QCH_CON_LH_AXI_SI_LD1_DPUF1_DPUF0_QCH */
	PD_SAVE(CMU, 0x308c),	/* QCH_CON_PPMU_D0_DPUF1_QCH */
	PD_SAVE(CMU, 0x3090),	/* QCH_CON_PPMU_D1_DPUF1_QCH */
	PD_SAVE(CMU, 0x3094),	/* QCH_CON_SLH_AXI_MI_P_DPUF1_QCH */
	PD_SAVE(CMU, 0x3098),	/* QCH_CON_SSMT_D0_DPUF1_QCH */
	PD_SAVE(CMU, 0x309c),	/* QCH_CON_SSMT_D1_DPUF1_QCH */
	PD_SAVE(CMU, 0x30a0),	/* QCH_CON_SYSMMU_S0_DPUF1_QCH_S0 */
	PD_SAVE(CMU, 0x30a4),	/* QCH_CON_SYSMMU_S0_PMMU0_DPUF1_QCH_S0 */
	PD_SAVE(CMU, 0x30a8),	/* QCH_CON_SYSMMU_S0_PMMU1_DPUF1_QCH_S0 */
	PD_SAVE(CMU, 0x30ac),	/* QCH_CON_SYSREG_DPUF1_QCH */
	PD_SAVE(CMU, 0x0800),	/* DPUF1_CMU_DPUF1_CONTROLLER_OPTION */
	PD_SAVE(SYSREG, 0x0104),	/* BUS_COMPONENT_DRCG_EN */
	PD_SAVE(SYSREG, 0x0108),	/* MEMCLK */
};

/* MFC */
static const struct exynos_pd_step zumapro_mfc_save[] = {
	PD_SAVE(CMU, 0x1800),	/* CLK_CON_DIV_DIV_CLK_MFC_NOCP */
	PD_SAVE(CMU, 0x0600),	/* PLL_CON0_MUX_CLKCMU_MFC_MFC_USER */
	PD_SAVE(CMU, 0x300c),	/* QCH_CON_D_TZPC_MFC_QCH */
	PD_SAVE(CMU, 0x3010),	/* QCH_CON_GPC_MFC_QCH */
	PD_SAVE(CMU, 0x3014),	/* QCH_CON_LH_AXI_SI_D0_MFC_QCH */
	PD_SAVE(CMU, 0x3018),	/* QCH_CON_LH_AXI_SI_D1_MFC_QCH */
	PD_SAVE(CMU, 0x301c),	/* QCH_CON_MFC_CMU_MFC_QCH */
	PD_SAVE(CMU, 0x3020),	/* QCH_CON_MFC_QCH */
	PD_SAVE(CMU, 0x3024),	/* QCH_CON_PPMU_D0_MFC_QCH */
	PD_SAVE(CMU, 0x3028),	/* QCH_CON_PPMU_D1_MFC_QCH */
	PD_SAVE(CMU, 0x302c),	/* QCH_CON_RSTNSYNC_CLK_MFC_NOCD_SW_RESET_QCH */
	PD_SAVE(CMU, 0x3034),	/* QCH_CON_SLH_AXI_MI_P_MFC_QCH */
	PD_SAVE(CMU, 0x3038),	/* QCH_CON_SSMT_D0_MFC_QCH */
	PD_SAVE(CMU, 0x303c),	/* QCH_CON_SSMT_D1_MFC_QCH */
	PD_SAVE(CMU, 0x3040),	/* QCH_CON_SYSMMU_S0_MFC_QCH */
	PD_SAVE(CMU, 0x3044),	/* QCH_CON_SYSMMU_S0_PMMU0_MFC_QCH */
	PD_SAVE(CMU, 0x3048),	/* QCH_CON_SYSMMU_S0_PMMU1_MFC_QCH */
	PD_SAVE(CMU, 0x304c),	/* QCH_CON_SYSREG_MFC_QCH */
	PD_SAVE(CMU, 0x0800),	/* MFC_CMU_MFC_CONTROLLER_OPTION */
	PD_SAVE(SYSREG, 0x0104),	/* BUS_COMPONENT_DRCG_EN */
	PD_SAVE(SYSREG, 0x0108),	/* MEMCLK */
};

/* HSI1 */
static const struct exynos_pd_step zumapro_hsi1_save[] = {
	PD_SAVE(CMU, 0x1800),	/* CLK_CON_DIV_DIV_CLK_HSI1_NOCP */
	PD_SAVE(CMU, 0x1804),	/* CLK_CON_DIV_DIV_CLK_HSI1_NOC_LH */
	PD_SAVE(CMU, 0x1808),	/* CLK_CON_DIV_CLK_HSI1_ALT */
	PD_SAVE(CMU, 0x1000),	/* CLK_CON_MUX_MUX_CLK_HSI1_NOC */
	PD_SAVE(CMU, 0x0600),	/* PLL_CON0_MUX_CLKCMU_HSI1_NOC_USER */
	PD_SAVE(CMU, 0x0610),	/* PLL_CON0_MUX_CLKCMU_HSI1_PCIE_USER */
	PD_SAVE(CMU, 0x0620),	/* PLL_CON0_MUX_CLKCMU_HSI1_ALT_USER */
	PD_SAVE(CMU, 0x3000),	/* DMYQCH_CON_PCIE_GEN3_0_QCH_REF */
	PD_SAVE(CMU, 0x3004),	/* QCH_CON_SYSMMU_S0_PMMU0_HSI1_QCH_S0 */
	PD_SAVE(CMU, 0x3034),	/* QCH_CON_D_TZPC_HSI1_QCH */
	PD_SAVE(CMU, 0x3038),	/* QCH_CON_GPC_HSI1_QCH */
	PD_SAVE(CMU, 0x303c),	/* QCH_CON_GPIO_HSI1_QCH */
	PD_SAVE(CMU, 0x3040),	/* QCH_CON_HSI1_CMU_HSI1_QCH */
	PD_SAVE(CMU, 0x3044),	/* QCH_CON_LH_ACEL_SI_D_HSI1_QCH */
	PD_SAVE(CMU, 0x3048),	/* QCH_CON_LH_AXI_MI_LP_AOC_HSI1_CU_QCH */
	PD_SAVE(CMU, 0x304c),	/* QCH_CON_LH_AXI_MI_P_HSI1_CU_QCH */
	PD_SAVE(CMU, 0x3050),	/* QCH_CON_LH_AXI_MI_LP_CPUCL0_HSI1_CU_QCH */
	PD_SAVE(CMU, 0x3054),	/* QCH_CON_LH_AXI_SI_LD_HSI1_AOC_QCH */
	PD_SAVE(CMU, 0x3058),	/* QCH_CON_LH_AXI_SI_LP_AOC_HSI1_CU_QCH */
	PD_SAVE(CMU, 0x305c),	/* QCH_CON_LH_AXI_SI_P_HSI1_CU_QCH */
	PD_SAVE(CMU, 0x3060),	/* QCH_CON_LH_AXI_SI_LP_CPUCL0_HSI1_CU_QCH */
	PD_SAVE(CMU, 0x3064),	/* QCH_CON_PCIE_GEN3_0_QCH_APB */
	PD_SAVE(CMU, 0x306c),	/* QCH_CON_PCIE_GEN3_0_QCH_AXI */
	PD_SAVE(CMU, 0x3074),	/* QCH_CON_PCIE_GEN3_0_QCH_DBI */
	PD_SAVE(CMU, 0x307c),	/* QCH_CON_PCIE_GEN3_0_QCH_PCS_APB */
	PD_SAVE(CMU, 0x3080),	/* QCH_CON_PCIE_GEN3_0_QCH_PMA_APB */
	PD_SAVE(CMU, 0x3084),	/* QCH_CON_PCIE_GEN3_0_QCH_UDBG */
	PD_SAVE(CMU, 0x3088),	/* QCH_CON_PCIE_IA_GEN3A_0_QCH */
	PD_SAVE(CMU, 0x3090),	/* QCH_CON_PPMU_HSI1_QCH */
	PD_SAVE(CMU, 0x309c),	/* QCH_CON_SLH_AXI_MI_LP_AOC_HSI1_QCH */
	PD_SAVE(CMU, 0x30a0),	/* QCH_CON_SLH_AXI_MI_P_HSI1_QCH */
	PD_SAVE(CMU, 0x30a4),	/* QCH_CON_LH_AXI_MI_LP_CPUCL0_HSI1_QCH */
	PD_SAVE(CMU, 0x30a8),	/* QCH_CON_SSMT_HSI1_QCH */
	PD_SAVE(CMU, 0x30ac),	/* QCH_CON_SSMT_PCIE_IA_GEN3A_0_QCH */
	PD_SAVE(CMU, 0x30b4),	/* QCH_CON_SYSMMU_S0_HSI1_QCH_S0 */
	PD_SAVE(CMU, 0x30bc),	/* QCH_CON_SYSREG_HSI1_QCH */
	PD_SAVE(CMU, 0x30c0),	/* QCH_CON_UASC_PCIE_GEN3A_DBI_0_QCH */
	PD_SAVE(CMU, 0x30c4),	/* QCH_CON_UASC_PCIE_GEN3A_SLV_0_QCH */
	PD_SAVE(CMU, 0x0800),	/* HSI1_CMU_HSI1_CONTROLLER_OPTION */
	PD_SAVE(SYSREG, 0x0104),	/* BUS_COMPONENT_DRCG_EN */
	PD_SAVE(SYSREG, 0x0108),	/* MEMCLK */
};

/*
 * The domains below have no clock provider in this tree, so each carries
 * the vendor's save list for its CMU and SYSREG: dividers, muxes, the
 * Q-channels, the controller options, DRCG and MEMCLK, and for the blocks
 * with a PLL of their own a lock wait in the restore.  Generated from the
 * vendor's flexpmu_cal_local_zuma.h by tools/pd-tables-from-pmucal.py in
 * the tegu repository; the generator reproduces the hand-ported G3D list
 * above step for step.  AOC has no list: its firmware owns CMU_AOC.
 */

/* G2D */
static const struct exynos_pd_step zumapro_g2d_save[] = {
	PD_SAVE(CMU, 0x1800),	/* CLK_CON_DIV_DIV_CLK_G2D_NOCP */
	PD_SAVE(CMU, 0x0600),	/* PLL_CON0_MUX_CLKCMU_G2D_G2D_USER */
	PD_SAVE(CMU, 0x0610),	/* PLL_CON0_MUX_CLKCMU_G2D_JPEG_USER */
	PD_SAVE(CMU, 0x3030),	/* QCH_CON_D_TZPC_G2D_QCH */
	PD_SAVE(CMU, 0x3034),	/* QCH_CON_G2D_CMU_G2D_QCH */
	PD_SAVE(CMU, 0x3038),	/* QCH_CON_G2D_QCH */
	PD_SAVE(CMU, 0x303c),	/* QCH_CON_GPC_G2D_QCH */
	PD_SAVE(CMU, 0x3040),	/* QCH_CON_JPEG_QCH */
	PD_SAVE(CMU, 0x3044),	/* QCH_CON_LH_ACEL_SI_D2_G2D_QCH */
	PD_SAVE(CMU, 0x3048),	/* QCH_CON_LH_AST_MI_ID_G2D0_JPEG_QCH */
	PD_SAVE(CMU, 0x304c),	/* QCH_CON_LH_AST_MI_ID_G2D1_JPEG_QCH */
	PD_SAVE(CMU, 0x3050),	/* QCH_CON_LH_AST_MI_ID_JPEG_G2D0_QCH */
	PD_SAVE(CMU, 0x3054),	/* QCH_CON_LH_AST_MI_ID_JPEG_G2D1_QCH */
	PD_SAVE(CMU, 0x3058),	/* QCH_CON_LH_AST_SI_ID_G2D0_JPEG_QCH */
	PD_SAVE(CMU, 0x305c),	/* QCH_CON_LH_AST_SI_ID_G2D1_JPEG_QCH */
	PD_SAVE(CMU, 0x3060),	/* QCH_CON_LH_AST_SI_ID_JPEG_G2D0_QCH */
	PD_SAVE(CMU, 0x3064),	/* QCH_CON_LH_AST_SI_ID_JPEG_G2D1_QCH */
	PD_SAVE(CMU, 0x3068),	/* QCH_CON_LH_AXI_SI_D0_G2D_QCH */
	PD_SAVE(CMU, 0x306c),	/* QCH_CON_LH_AXI_SI_D1_G2D_QCH */
	PD_SAVE(CMU, 0x3070),	/* QCH_CON_PPMU_D0_G2D_QCH */
	PD_SAVE(CMU, 0x3074),	/* QCH_CON_PPMU_D1_G2D_QCH */
	PD_SAVE(CMU, 0x3078),	/* QCH_CON_PPMU_D2_G2D_QCH */
	PD_SAVE(CMU, 0x307c),	/* QCH_CON_SLH_AXI_MI_P_G2D_QCH */
	PD_SAVE(CMU, 0x3080),	/* QCH_CON_SSMT_D0_G2D_QCH */
	PD_SAVE(CMU, 0x3084),	/* QCH_CON_SSMT_D1_G2D_QCH */
	PD_SAVE(CMU, 0x3088),	/* QCH_CON_SSMT_D2_G2D_QCH */
	PD_SAVE(CMU, 0x308c),	/* QCH_CON_SYSMMU_S0_G2D_QCH */
	PD_SAVE(CMU, 0x3090),	/* QCH_CON_SYSMMU_S0_PMMU0_G2D_QCH */
	PD_SAVE(CMU, 0x3094),	/* QCH_CON_SYSMMU_S0_PMMU1_G2D_QCH */
	PD_SAVE(CMU, 0x3098),	/* QCH_CON_SYSMMU_S0_PMMU2_G2D_QCH */
	PD_SAVE(CMU, 0x309c),	/* QCH_CON_SYSREG_G2D_QCH */
	PD_SAVE(CMU, 0x0800),	/* G2D_CMU_G2D_CONTROLLER_OPTION */
	PD_SAVE(SYSREG, 0x0104),	/* BUS_COMPONENT_DRCG_EN */
	PD_SAVE(SYSREG, 0x0108),	/* MEMCLK */
};

/* GDC */
static const struct exynos_pd_step zumapro_gdc_save[] = {
	PD_SAVE(CMU, 0x1800),	/* CLK_CON_DIV_DIV_CLK_GDC_NOCP */
	PD_SAVE(CMU, 0x0600),	/* PLL_CON0_MUX_CLKCMU_GDC_GDC0_USER */
	PD_SAVE(CMU, 0x0610),	/* PLL_CON0_MUX_CLKCMU_GDC_GDC1_USER */
	PD_SAVE(CMU, 0x0620),	/* PLL_CON0_MUX_CLKCMU_GDC_LME_USER */
	PD_SAVE(CMU, 0x3034),	/* QCH_CON_D_TZPC_GDC_QCH */
	PD_SAVE(CMU, 0x3038),	/* QCH_CON_GDC0_QCH_C2CLK */
	PD_SAVE(CMU, 0x303c),	/* QCH_CON_GDC0_QCH_CLK */
	PD_SAVE(CMU, 0x3040),	/* QCH_CON_GDC1_QCH_C2CLK */
	PD_SAVE(CMU, 0x3044),	/* QCH_CON_GDC1_QCH_CLK */
	PD_SAVE(CMU, 0x3048),	/* QCH_CON_GDC_CMU_GDC_QCH */
	PD_SAVE(CMU, 0x304c),	/* QCH_CON_GPC_GDC_QCH */
	PD_SAVE(CMU, 0x3050),	/* QCH_CON_LH_AST_MI_ID_GDC0_GDC1_QCH */
	PD_SAVE(CMU, 0x3054),	/* QCH_CON_LH_AST_MI_ID_GDC1_GDC0_QCH */
	PD_SAVE(CMU, 0x3058),	/* QCH_CON_LH_AST_MI_ID_GDC1_LME_QCH */
	PD_SAVE(CMU, 0x305c),	/* QCH_CON_LH_AST_MI_ID_LME_GDC1_QCH */
	PD_SAVE(CMU, 0x3060),	/* QCH_CON_LH_AST_SI_ID_GDC0_GDC1_QCH */
	PD_SAVE(CMU, 0x3064),	/* QCH_CON_LH_AST_SI_ID_GDC1_GDC0_QCH */
	PD_SAVE(CMU, 0x3068),	/* QCH_CON_LH_AST_SI_ID_GDC1_LME_QCH */
	PD_SAVE(CMU, 0x306c),	/* QCH_CON_LH_AST_SI_ID_LME_GDC1_QCH */
	PD_SAVE(CMU, 0x3070),	/* QCH_CON_LH_AXI_MI_LD_RGBP_GDC_QCH */
	PD_SAVE(CMU, 0x3074),	/* QCH_CON_LH_AXI_SI_D0_GDC_QCH */
	PD_SAVE(CMU, 0x3078),	/* QCH_CON_LH_AXI_SI_D1_GDC_QCH */
	PD_SAVE(CMU, 0x307c),	/* QCH_CON_LH_AXI_SI_D2_GDC_QCH */
	PD_SAVE(CMU, 0x3080),	/* QCH_CON_LME_QCH_CLK */
	PD_SAVE(CMU, 0x3084),	/* QCH_CON_PPMU_D0_GDC0_QCH */
	PD_SAVE(CMU, 0x3088),	/* QCH_CON_PPMU_D0_GDC1_QCH */
	PD_SAVE(CMU, 0x308c),	/* QCH_CON_PPMU_D2_GDC0_QCH */
	PD_SAVE(CMU, 0x3090),	/* QCH_CON_PPMU_D2_GDC1_QCH */
	PD_SAVE(CMU, 0x3094),	/* QCH_CON_PPMU_D4_GDC0_QCH */
	PD_SAVE(CMU, 0x3098),	/* QCH_CON_PPMU_D4_GDC1_QCH */
	PD_SAVE(CMU, 0x309c),	/* QCH_CON_PPMU_D_LME_QCH */
	PD_SAVE(CMU, 0x30a0),	/* QCH_CON_QE_D0_GDC0_QCH */
	PD_SAVE(CMU, 0x30a4),	/* QCH_CON_QE_D0_GDC1_QCH */
	PD_SAVE(CMU, 0x30a8),	/* QCH_CON_QE_D2_GDC0_QCH */
	PD_SAVE(CMU, 0x30ac),	/* QCH_CON_QE_D2_GDC1_QCH */
	PD_SAVE(CMU, 0x30b0),	/* QCH_CON_QE_D4_GDC0_QCH */
	PD_SAVE(CMU, 0x30b4),	/* QCH_CON_QE_D4_GDC1_QCH */
	PD_SAVE(CMU, 0x30b8),	/* QCH_CON_SLH_AXI_MI_P_GDC_QCH */
	PD_SAVE(CMU, 0x30bc),	/* QCH_CON_SSMT_D0_GDC0_QCH */
	PD_SAVE(CMU, 0x30c0),	/* QCH_CON_SSMT_D0_GDC1_QCH */
	PD_SAVE(CMU, 0x30c4),	/* QCH_CON_SSMT_D2_GDC0_QCH */
	PD_SAVE(CMU, 0x30c8),	/* QCH_CON_SSMT_D2_GDC1_QCH */
	PD_SAVE(CMU, 0x30cc),	/* QCH_CON_SSMT_D4_GDC0_QCH */
	PD_SAVE(CMU, 0x30d0),	/* QCH_CON_SSMT_D4_GDC1_QCH */
	PD_SAVE(CMU, 0x30d4),	/* QCH_CON_SSMT_D_LME_QCH */
	PD_SAVE(CMU, 0x30d8),	/* QCH_CON_SYSMMU_S0_GDC_QCH_S0 */
	PD_SAVE(CMU, 0x30dc),	/* QCH_CON_SYSMMU_S0_PMMU0_GDC_QCH_S0 */
	PD_SAVE(CMU, 0x30e0),	/* QCH_CON_SYSMMU_S0_PMMU1_GDC_QCH_S0 */
	PD_SAVE(CMU, 0x30e4),	/* QCH_CON_SYSMMU_S0_PMMU2_GDC_QCH_S0 */
	PD_SAVE(CMU, 0x30e8),	/* QCH_CON_SYSREG_GDC_QCH */
	PD_SAVE(CMU, 0x0800),	/* GDC_CMU_GDC_CONTROLLER_OPTION */
	PD_SAVE(SYSREG, 0x0104),	/* BUS_COMPONENT_DRCG_EN0 */
	PD_SAVE(SYSREG, 0x0400),	/* BUS_COMPONENT_DRCG_EN1 */
	PD_SAVE(SYSREG, 0x010c),	/* MEMCLK */
};

/* GSE */
static const struct exynos_pd_step zumapro_gse_save[] = {
	PD_SAVE(CMU, 0x1800),	/* CLK_CON_DIV_DIV_CLK_GSE_NOCP */
	PD_SAVE(CMU, 0x0600),	/* PLL_CON0_MUX_CLKCMU_GSE_NOC_USER */
	PD_SAVE(CMU, 0x3010),	/* QCH_CON_D_TZPC_GSE_QCH */
	PD_SAVE(CMU, 0x3014),	/* QCH_CON_GPC_GSE_QCH */
	PD_SAVE(CMU, 0x3018),	/* QCH_CON_GSE_CMU_GSE_QCH */
	PD_SAVE(CMU, 0x301c),	/* QCH_CON_GSE_QCH_GSE */
	PD_SAVE(CMU, 0x3020),	/* QCH_CON_GSE_QCH_GSE_VOTF */
	PD_SAVE(CMU, 0x3024),	/* QCH_CON_LH_AST_MI_L_OTF_TNR_GSE_QCH */
	PD_SAVE(CMU, 0x3028),	/* QCH_CON_LH_AST_MI_L_OTF_YUVP_GSE_QCH */
	PD_SAVE(CMU, 0x302c),	/* QCH_CON_LH_AXI_SI_D_GSE_QCH */
	PD_SAVE(CMU, 0x3030),	/* QCH_CON_PPMU_D0_GSE_QCH */
	PD_SAVE(CMU, 0x3034),	/* QCH_CON_PPMU_D1_GSE_QCH */
	PD_SAVE(CMU, 0x3038),	/* QCH_CON_PPMU_D2_GSE_QCH */
	PD_SAVE(CMU, 0x303c),	/* QCH_CON_QE_D0_GSE_QCH */
	PD_SAVE(CMU, 0x3040),	/* QCH_CON_QE_D1_GSE_QCH */
	PD_SAVE(CMU, 0x3044),	/* QCH_CON_QE_D2_GSE_QCH */
	PD_SAVE(CMU, 0x3048),	/* QCH_CON_SLH_AXI_MI_P_GSE_QCH */
	PD_SAVE(CMU, 0x304c),	/* QCH_CON_SSMT_D0_GSE_QCH */
	PD_SAVE(CMU, 0x3050),	/* QCH_CON_SSMT_D1_GSE_QCH */
	PD_SAVE(CMU, 0x3054),	/* QCH_CON_SSMT_D2_GSE_QCH */
	PD_SAVE(CMU, 0x3058),	/* QCH_CON_SYSMMU_S0_GSE_QCH_S0 */
	PD_SAVE(CMU, 0x305c),	/* QCH_CON_SYSMMU_S0_PMMU0_GSE_QCH_S0 */
	PD_SAVE(CMU, 0x3060),	/* QCH_CON_SYSREG_GSE_QCH */
	PD_SAVE(CMU, 0x0800),	/* GSE_CMU_GSE_CONTROLLER_OPTION */
	PD_SAVE(SYSREG, 0x0104),	/* BUS_COMPONENT_DRCG_EN */
	PD_SAVE(SYSREG, 0x0108),	/* MEMCLK */
};

/* MCSC */
static const struct exynos_pd_step zumapro_mcsc_save[] = {
	PD_SAVE(CMU, 0x1800),	/* CLK_CON_DIV_DIV_CLK_MCSC_NOCP */
	PD_SAVE(CMU, 0x0610),	/* PLL_CON0_MUX_CLKCMU_MCSC_NOC_USER */
	PD_SAVE(CMU, 0x3014),	/* QCH_CON_D_TZPC_MCSC_QCH */
	PD_SAVE(CMU, 0x3018),	/* QCH_CON_GPC_MCSC_QCH */
	PD_SAVE(CMU, 0x301c),	/* QCH_CON_LH_AST_MI_L_OTF_TNR_MCSC_QCH */
	PD_SAVE(CMU, 0x3020),	/* QCH_CON_LH_AST_MI_L_OTF_YUVP_MCSC_QCH */
	PD_SAVE(CMU, 0x3024),	/* QCH_CON_LH_AXI_SI_D0_MCSC_QCH */
	PD_SAVE(CMU, 0x3028),	/* QCH_CON_LH_AXI_SI_D1_MCSC_QCH */
	PD_SAVE(CMU, 0x302c),	/* QCH_CON_MCSC_CMU_MCSC_QCH */
	PD_SAVE(CMU, 0x3030),	/* QCH_CON_MCSC_QCH */
	PD_SAVE(CMU, 0x3034),	/* QCH_CON_MCSC_QCH_C2R */
	PD_SAVE(CMU, 0x3038),	/* QCH_CON_PPMU_D0_MCSC_QCH */
	PD_SAVE(CMU, 0x303c),	/* QCH_CON_PPMU_D1_MCSC_QCH */
	PD_SAVE(CMU, 0x3040),	/* QCH_CON_PPMU_D2_MCSC_QCH */
	PD_SAVE(CMU, 0x3044),	/* QCH_CON_PPMU_D3_MCSC_QCH */
	PD_SAVE(CMU, 0x3048),	/* QCH_CON_PPMU_D4_MCSC_QCH */
	PD_SAVE(CMU, 0x304c),	/* QCH_CON_PPMU_D5_MCSC_QCH */
	PD_SAVE(CMU, 0x3050),	/* QCH_CON_PPMU_D6_MCSC_QCH */
	PD_SAVE(CMU, 0x3054),	/* QCH_CON_QE_D0_MCSC_QCH */
	PD_SAVE(CMU, 0x3058),	/* QCH_CON_QE_D1_MCSC_QCH */
	PD_SAVE(CMU, 0x305c),	/* QCH_CON_QE_D2_MCSC_QCH */
	PD_SAVE(CMU, 0x3060),	/* QCH_CON_QE_D3_MCSC_QCH */
	PD_SAVE(CMU, 0x3064),	/* QCH_CON_QE_D4_MCSC_QCH */
	PD_SAVE(CMU, 0x3068),	/* QCH_CON_QE_D5_MCSC_QCH */
	PD_SAVE(CMU, 0x306c),	/* QCH_CON_QE_D6_MCSC_QCH */
	PD_SAVE(CMU, 0x3070),	/* QCH_CON_SLH_AXI_MI_P_MCSC_QCH */
	PD_SAVE(CMU, 0x3074),	/* QCH_CON_SSMT_D0_MCSC_QCH */
	PD_SAVE(CMU, 0x3078),	/* QCH_CON_SSMT_D1_MCSC_QCH */
	PD_SAVE(CMU, 0x307c),	/* QCH_CON_SSMT_D2_MCSC_QCH */
	PD_SAVE(CMU, 0x3080),	/* QCH_CON_SSMT_D3_MCSC_QCH */
	PD_SAVE(CMU, 0x3084),	/* QCH_CON_SSMT_D4_MCSC_QCH */
	PD_SAVE(CMU, 0x3088),	/* QCH_CON_SSMT_D5_MCSC_QCH */
	PD_SAVE(CMU, 0x308c),	/* QCH_CON_SSMT_D6_MCSC_QCH */
	PD_SAVE(CMU, 0x3090),	/* QCH_CON_SYSMMU_S0_MCSC_QCH_S0 */
	PD_SAVE(CMU, 0x3094),	/* QCH_CON_SYSMMU_S0_PMMU0_MCSC_QCH_S0 */
	PD_SAVE(CMU, 0x3098),	/* QCH_CON_SYSMMU_S0_PMMU1_MCSC_QCH_S0 */
	PD_SAVE(CMU, 0x309c),	/* QCH_CON_SYSREG_MCSC_QCH */
	PD_SAVE(CMU, 0x0800),	/* MCSC_CMU_MCSC_CONTROLLER_OPTION */
	PD_SAVE(SYSREG, 0x0104),	/* BUS_COMPONENT_DRCG_EN */
	PD_SAVE(SYSREG, 0x0108),	/* MEMCLK */
};

/* RGBP */
static const struct exynos_pd_step zumapro_rgbp_save[] = {
	PD_SAVE(CMU, 0x1800),	/* CLK_CON_DIV_DIV_CLK_RGBP_NOCP */
	PD_SAVE(CMU, 0x0600),	/* PLL_CON0_MUX_CLKCMU_RGBP_MCFP_USER */
	PD_SAVE(CMU, 0x0610),	/* PLL_CON0_MUX_CLKCMU_RGBP_RGBP_USER */
	PD_SAVE(CMU, 0x3030),	/* QCH_CON_D_TZPC_RGBP_QCH */
	PD_SAVE(CMU, 0x3034),	/* QCH_CON_GPC_RGBP_QCH */
	PD_SAVE(CMU, 0x3038),	/* QCH_CON_LH_AST_MI_I_RGBP_MCFP_QCH */
	PD_SAVE(CMU, 0x303c),	/* QCH_CON_LH_AST_SI_I_RGBP_MCFP_QCH */
	PD_SAVE(CMU, 0x3040),	/* QCH_CON_LH_AST_SI_L_OTF_RGBP_YUVP_QCH */
	PD_SAVE(CMU, 0x3044),	/* QCH_CON_LH_AXI_SI_D0_RGBP_QCH */
	PD_SAVE(CMU, 0x3048),	/* QCH_CON_LH_AXI_SI_D1_RGBP_QCH */
	PD_SAVE(CMU, 0x304c),	/* QCH_CON_LH_AXI_SI_D2_RGBP_QCH */
	PD_SAVE(CMU, 0x3050),	/* QCH_CON_LH_AXI_SI_D3_RGBP_QCH */
	PD_SAVE(CMU, 0x3054),	/* QCH_CON_LH_AXI_SI_D4_RGBP_QCH */
	PD_SAVE(CMU, 0x3058),	/* QCH_CON_LH_AXI_SI_D5_RGBP_QCH */
	PD_SAVE(CMU, 0x305c),	/* QCH_CON_LH_AXI_SI_D6_RGBP_QCH */
	PD_SAVE(CMU, 0x3060),	/* QCH_CON_LH_AXI_SI_LD_RGBP_GDC_QCH */
	PD_SAVE(CMU, 0x3064),	/* QCH_CON_MCFP_QCH_CLK */
	PD_SAVE(CMU, 0x3068),	/* QCH_CON_PPMU_D0_MCFP_QCH */
	PD_SAVE(CMU, 0x306c),	/* QCH_CON_PPMU_D0_RGBP_QCH */
	PD_SAVE(CMU, 0x3070),	/* QCH_CON_PPMU_D1_RGBP_QCH */
	PD_SAVE(CMU, 0x3074),	/* QCH_CON_PPMU_D2_MCFP_QCH */
	PD_SAVE(CMU, 0x3078),	/* QCH_CON_PPMU_D2_RGBP_QCH */
	PD_SAVE(CMU, 0x307c),	/* QCH_CON_PPMU_D3_MCFP_QCH */
	PD_SAVE(CMU, 0x3080),	/* QCH_CON_PPMU_D4_MCFP_QCH */
	PD_SAVE(CMU, 0x3084),	/* QCH_CON_PPMU_D5_MCFP_QCH */
	PD_SAVE(CMU, 0x3088),	/* QCH_CON_QE_D0_RGBP_QCH */
	PD_SAVE(CMU, 0x308c),	/* QCH_CON_QE_D10_MCFP_QCH */
	PD_SAVE(CMU, 0x3090),	/* QCH_CON_QE_D11_MCFP_QCH */
	PD_SAVE(CMU, 0x3094),	/* QCH_CON_QE_D1_RGBP_QCH */
	PD_SAVE(CMU, 0x3098),	/* QCH_CON_QE_D2_RGBP_QCH */
	PD_SAVE(CMU, 0x309c),	/* QCH_CON_QE_D3_RGBP_QCH */
	PD_SAVE(CMU, 0x30a0),	/* QCH_CON_QE_D4_MCFP_QCH */
	PD_SAVE(CMU, 0x30a4),	/* QCH_CON_QE_D4_RGBP_QCH */
	PD_SAVE(CMU, 0x30a8),	/* QCH_CON_QE_D5_MCFP_QCH */
	PD_SAVE(CMU, 0x30ac),	/* QCH_CON_QE_D5_RGBP_QCH */
	PD_SAVE(CMU, 0x30b0),	/* QCH_CON_QE_D6_MCFP_QCH */
	PD_SAVE(CMU, 0x30b4),	/* QCH_CON_QE_D6_RGBP_QCH */
	PD_SAVE(CMU, 0x30b8),	/* QCH_CON_QE_D7_MCFP_QCH */
	PD_SAVE(CMU, 0x30bc),	/* QCH_CON_QE_D8_MCFP_QCH */
	PD_SAVE(CMU, 0x30c0),	/* QCH_CON_QE_D9_MCFP_QCH */
	PD_SAVE(CMU, 0x30c4),	/* QCH_CON_RGBP_CMU_RGBP_QCH */
	PD_SAVE(CMU, 0x30c8),	/* QCH_CON_RGBP_QCH */
	PD_SAVE(CMU, 0x30cc),	/* QCH_CON_RGBP_QCH_VOTF0 */
	PD_SAVE(CMU, 0x30d0),	/* QCH_CON_SLH_AXI_MI_P_RGBP_QCH */
	PD_SAVE(CMU, 0x30d4),	/* QCH_CON_SSMT_D0_MCFP_QCH */
	PD_SAVE(CMU, 0x30d8),	/* QCH_CON_SSMT_D0_RGBP_QCH */
	PD_SAVE(CMU, 0x30dc),	/* QCH_CON_SSMT_D1_RGBP_QCH */
	PD_SAVE(CMU, 0x30e0),	/* QCH_CON_SSMT_D2_MCFP_QCH */
	PD_SAVE(CMU, 0x30e4),	/* QCH_CON_SSMT_D2_RGBP_QCH */
	PD_SAVE(CMU, 0x30e8),	/* QCH_CON_SSMT_D3_MCFP_QCH */
	PD_SAVE(CMU, 0x30ec),	/* QCH_CON_SSMT_D4_MCFP_QCH */
	PD_SAVE(CMU, 0x30f0),	/* QCH_CON_SSMT_D5_MCFP_QCH */
	PD_SAVE(CMU, 0x30f4),	/* QCH_CON_SYSMMU_S0_PMMU0_RGBP_QCH_S0 */
	PD_SAVE(CMU, 0x30f8),	/* QCH_CON_SYSMMU_S0_PMMU1_RGBP_QCH_S0 */
	PD_SAVE(CMU, 0x30fc),	/* QCH_CON_SYSMMU_S0_RGBP_QCH_S0 */
	PD_SAVE(CMU, 0x3100),	/* QCH_CON_SYSMMU_S1_PMMU0_RGBP_QCH_S0 */
	PD_SAVE(CMU, 0x3104),	/* QCH_CON_SYSMMU_S1_PMMU1_RGBP_QCH_S0 */
	PD_SAVE(CMU, 0x3108),	/* QCH_CON_SYSMMU_S1_PMMU2_RGBP_QCH_S0 */
	PD_SAVE(CMU, 0x310c),	/* QCH_CON_SYSMMU_S1_PMMU3_RGBP_QCH_S0 */
	PD_SAVE(CMU, 0x3110),	/* QCH_CON_SYSMMU_S1_PMMU4_RGBP_QCH_S0 */
	PD_SAVE(CMU, 0x3114),	/* QCH_CON_SYSMMU_S1_RGBP_QCH_S0 */
	PD_SAVE(CMU, 0x311c),	/* QCH_CON_SYSREG_RGBP_QCH */
	PD_SAVE(CMU, 0x0800),	/* RGBP_CMU_RGBP_CONTROLLER_OPTION */
	PD_SAVE(SYSREG, 0x0104),	/* BUS_COMPONENT_DRCG_EN0 */
	PD_SAVE(SYSREG, 0x0400),	/* BUS_COMPONENT_DRCG_EN1 */
	PD_SAVE(SYSREG, 0x0108),	/* MEMCLK */
};

/* TNR */
static const struct exynos_pd_step zumapro_tnr_save[] = {
	PD_SAVE(CMU, 0x1800),	/* CLK_CON_DIV_DIV_CLK_TNR_NOCP */
	PD_SAVE(CMU, 0x0600),	/* PLL_CON0_MUX_CLKCMU_TNR_ALIGN_USER */
	PD_SAVE(CMU, 0x0610),	/* PLL_CON0_MUX_CLKCMU_TNR_MERGE_USER */
	PD_SAVE(CMU, 0x3028),	/* QCH_CON_D_TZPC_TNR_QCH */
	PD_SAVE(CMU, 0x302c),	/* QCH_CON_GPC_TNR_QCH */
	PD_SAVE(CMU, 0x3030),	/* QCH_CON_GTNR_ALIGN_QCH_MSA */
	PD_SAVE(CMU, 0x3034),	/* QCH_CON_GTNR_MERGE_QCH_00 */
	PD_SAVE(CMU, 0x3038),	/* QCH_CON_GTNR_MERGE_QCH_01 */
	PD_SAVE(CMU, 0x303c),	/* QCH_CON_LH_AST_MI_L_OTF_YUVP_TNR_QCH */
	PD_SAVE(CMU, 0x3040),	/* QCH_CON_LH_AST_SI_L_OTF_TNR_GSE_QCH */
	PD_SAVE(CMU, 0x3044),	/* QCH_CON_LH_AST_SI_L_OTF_TNR_MCSC_QCH */
	PD_SAVE(CMU, 0x3048),	/* QCH_CON_LH_AXI_SI_D0_TNR_QCH */
	PD_SAVE(CMU, 0x304c),	/* QCH_CON_LH_AXI_SI_D1_TNR_QCH */
	PD_SAVE(CMU, 0x3050),	/* QCH_CON_LH_AXI_SI_D2_TNR_QCH */
	PD_SAVE(CMU, 0x3054),	/* QCH_CON_LH_AXI_SI_D3_TNR_QCH */
	PD_SAVE(CMU, 0x3058),	/* QCH_CON_LH_AXI_SI_D4_TNR_QCH */
	PD_SAVE(CMU, 0x305c),	/* QCH_CON_LH_AXI_SI_D5_TNR_QCH */
	PD_SAVE(CMU, 0x3060),	/* QCH_CON_PPMU_D0_TNR_QCH */
	PD_SAVE(CMU, 0x3064),	/* QCH_CON_PPMU_D10_TNRA_QCH_S0 */
	PD_SAVE(CMU, 0x3068),	/* QCH_CON_PPMU_D11_TNRA_QCH_S0 */
	PD_SAVE(CMU, 0x306c),	/* QCH_CON_PPMU_D1_TNR_QCH */
	PD_SAVE(CMU, 0x3070),	/* QCH_CON_PPMU_D2_TNR_QCH */
	PD_SAVE(CMU, 0x3074),	/* QCH_CON_PPMU_D3_TNR_QCH */
	PD_SAVE(CMU, 0x3078),	/* QCH_CON_PPMU_D4_TNR_QCH */
	PD_SAVE(CMU, 0x307c),	/* QCH_CON_PPMU_D5_TNR_QCH */
	PD_SAVE(CMU, 0x3080),	/* QCH_CON_PPMU_D6_TNR_QCH */
	PD_SAVE(CMU, 0x3084),	/* QCH_CON_PPMU_D7_TNR_QCH */
	PD_SAVE(CMU, 0x3088),	/* QCH_CON_PPMU_D8_TNR_QCH */
	PD_SAVE(CMU, 0x308c),	/* QCH_CON_PPMU_D9_TNR_QCH */
	PD_SAVE(CMU, 0x3090),	/* QCH_CON_QE_D0_TNR_QCH */
	PD_SAVE(CMU, 0x3094),	/* QCH_CON_QE_D10_TNRA_QCH */
	PD_SAVE(CMU, 0x3098),	/* QCH_CON_QE_D11_TNRA_QCH */
	PD_SAVE(CMU, 0x309c),	/* QCH_CON_QE_D1_TNR_QCH */
	PD_SAVE(CMU, 0x30a0),	/* QCH_CON_QE_D2_TNR_QCH */
	PD_SAVE(CMU, 0x30a4),	/* QCH_CON_QE_D3_TNR_QCH */
	PD_SAVE(CMU, 0x30a8),	/* QCH_CON_QE_D4_TNR_QCH */
	PD_SAVE(CMU, 0x30ac),	/* QCH_CON_QE_D5_TNR_QCH */
	PD_SAVE(CMU, 0x30b0),	/* QCH_CON_QE_D6_TNR_QCH */
	PD_SAVE(CMU, 0x30b4),	/* QCH_CON_QE_D7_TNR_QCH */
	PD_SAVE(CMU, 0x30b8),	/* QCH_CON_QE_D8_TNR_QCH */
	PD_SAVE(CMU, 0x30bc),	/* QCH_CON_QE_D9_TNR_QCH */
	PD_SAVE(CMU, 0x30c0),	/* QCH_CON_SLH_AXI_MI_P_TNR_QCH */
	PD_SAVE(CMU, 0x30c4),	/* QCH_CON_SSMT_D0_TNR_QCH */
	PD_SAVE(CMU, 0x30c8),	/* QCH_CON_SSMT_D10_TNRA_QCH */
	PD_SAVE(CMU, 0x30cc),	/* QCH_CON_SSMT_D11_TNRA_QCH */
	PD_SAVE(CMU, 0x30d0),	/* QCH_CON_SSMT_D1_TNR_QCH */
	PD_SAVE(CMU, 0x30d4),	/* QCH_CON_SSMT_D2_TNR_QCH */
	PD_SAVE(CMU, 0x30d8),	/* QCH_CON_SSMT_D3_TNR_QCH */
	PD_SAVE(CMU, 0x30dc),	/* QCH_CON_SSMT_D4_TNR_QCH */
	PD_SAVE(CMU, 0x30e0),	/* QCH_CON_SSMT_D5_TNR_QCH */
	PD_SAVE(CMU, 0x30e4),	/* QCH_CON_SSMT_D6_TNR_QCH */
	PD_SAVE(CMU, 0x30e8),	/* QCH_CON_SSMT_D7_TNR_QCH */
	PD_SAVE(CMU, 0x30ec),	/* QCH_CON_SSMT_D8_TNR_QCH */
	PD_SAVE(CMU, 0x30f0),	/* QCH_CON_SSMT_D9_TNR_QCH */
	PD_SAVE(CMU, 0x30f4),	/* QCH_CON_SYSMMU_S0_PMMU0_TNR_QCH_S0 */
	PD_SAVE(CMU, 0x30f8),	/* QCH_CON_SYSMMU_S0_PMMU1_TNR_QCH_S0 */
	PD_SAVE(CMU, 0x30fc),	/* QCH_CON_SYSMMU_S0_TNR_QCH_S0 */
	PD_SAVE(CMU, 0x3100),	/* QCH_CON_SYSMMU_S1_PMMU0_TNR_QCH_S0 */
	PD_SAVE(CMU, 0x3104),	/* QCH_CON_SYSMMU_S1_PMMU1_TNR_QCH_S0 */
	PD_SAVE(CMU, 0x3108),	/* QCH_CON_SYSMMU_S1_PMMU2_TNR_QCH_S0 */
	PD_SAVE(CMU, 0x310c),	/* QCH_CON_SYSMMU_S1_TNR_QCH_S0 */
	PD_SAVE(CMU, 0x3110),	/* QCH_CON_SYSMMU_S2_PMMU0_TNR_QCH_S0 */
	PD_SAVE(CMU, 0x3114),	/* QCH_CON_SYSMMU_S2_TNR_QCH_S0 */
	PD_SAVE(CMU, 0x3118),	/* QCH_CON_SYSREG_TNR_QCH */
	PD_SAVE(CMU, 0x311c),	/* QCH_CON_TNR_CMU_TNR_QCH */
	PD_SAVE(CMU, 0x0800),	/* TNR_CMU_TNR_CONTROLLER_OPTION */
	PD_SAVE(SYSREG, 0x0104),	/* BUS_COMPONENT_DRCG_EN0 */
	PD_SAVE(SYSREG, 0x010c),	/* BUS_COMPONENT_DRCG_EN1 */
	PD_SAVE(SYSREG, 0x0108),	/* MEMCLK */
};

/* YUVP */
static const struct exynos_pd_step zumapro_yuvp_save[] = {
	PD_SAVE(CMU, 0x1800),	/* CLK_CON_DIV_DIV_CLK_YUVP_NOCP */
	PD_SAVE(CMU, 0x0600),	/* PLL_CON0_MUX_CLKCMU_YUVP_NOC_USER */
	PD_SAVE(CMU, 0x3018),	/* QCH_CON_D_TZPC_YUVP_QCH */
	PD_SAVE(CMU, 0x301c),	/* QCH_CON_GPC_YUVP_QCH */
	PD_SAVE(CMU, 0x3020),	/* QCH_CON_LH_AST_MI_L_OTF_RGBP_YUVP_QCH */
	PD_SAVE(CMU, 0x3024),	/* QCH_CON_LH_AST_SI_L_OTF_YUVP_GSE_QCH */
	PD_SAVE(CMU, 0x3028),	/* QCH_CON_LH_AST_SI_L_OTF_YUVP_MCSC_QCH */
	PD_SAVE(CMU, 0x302c),	/* QCH_CON_LH_AST_SI_L_OTF_YUVP_TNR_QCH */
	PD_SAVE(CMU, 0x3030),	/* QCH_CON_LH_AXI_SI_D_YUVP_QCH */
	PD_SAVE(CMU, 0x3034),	/* QCH_CON_PPMU_D0_YUVP_QCH */
	PD_SAVE(CMU, 0x3038),	/* QCH_CON_PPMU_D1_YUVP_QCH */
	PD_SAVE(CMU, 0x303c),	/* QCH_CON_PPMU_D4_YUVP_QCH */
	PD_SAVE(CMU, 0x3040),	/* QCH_CON_QE_D0_YUVP_QCH */
	PD_SAVE(CMU, 0x3044),	/* QCH_CON_QE_D1_YUVP_QCH */
	PD_SAVE(CMU, 0x3048),	/* QCH_CON_QE_D4_YUVP_QCH */
	PD_SAVE(CMU, 0x304c),	/* QCH_CON_SLH_AXI_MI_P_YUVP_QCH */
	PD_SAVE(CMU, 0x3050),	/* QCH_CON_SSMT_D0_YUVP_QCH */
	PD_SAVE(CMU, 0x3054),	/* QCH_CON_SSMT_D1_YUVP_QCH */
	PD_SAVE(CMU, 0x3058),	/* QCH_CON_SSMT_D4_YUVP_QCH */
	PD_SAVE(CMU, 0x305c),	/* QCH_CON_SYSMMU_S0_PMMU0_YUVP_QCH_S0 */
	PD_SAVE(CMU, 0x3060),	/* QCH_CON_SYSMMU_S0_YUVP_QCH_S0 */
	PD_SAVE(CMU, 0x3064),	/* QCH_CON_SYSREG_YUVP_QCH */
	PD_SAVE(CMU, 0x3068),	/* QCH_CON_YUVP_CMU_YUVP_QCH */
	PD_SAVE(CMU, 0x306c),	/* QCH_CON_YUVP_QCH */
	PD_SAVE(CMU, 0x3070),	/* QCH_CON_YUVP_QCH_VOTF0 */
	PD_SAVE(CMU, 0x0800),	/* YUVP_CMU_YUVP_CONTROLLER_OPTION */
	PD_SAVE(SYSREG, 0x0104),	/* BUS_COMPONENT_DRCG_EN */
	PD_SAVE(SYSREG, 0x0108),	/* MEMCLK */
};

/* AUR */
static const struct exynos_pd_step zumapro_aur_save[] = {
	PD_SAVE(CMU, 0x0000),	/* PLL_LOCKTIME_PLL_AUR */
	PD_SAVE(CMU, 0x0080),	/* PLL_LOCKTIME_REG_PLL_AUR */
	PD_SAVE(CMU, 0x0108),	/* PLL_CON2_PLL_AUR */
	PD_SAVE(CMU, 0x0110),	/* PLL_CON4_PLL_AUR */
	PD_SAVE(CMU, 0x0114),	/* PLL_CON5_PLL_AUR */
	PD_SAVE(CMU, 0x011c),	/* PLL_CON7_PLL_AUR */
	PD_SAVE(CMU, 0x0120),	/* PLL_CON8_PLL_AUR */
	PD_SAVE(CMU, 0x0118),	/* PLL_CON6_PLL_AUR */
	PD_SKIP_IF(CMU, 0x0118, PLL_CON_ENABLE, 0),	/* PLL_CON6_PLL_AUR */
	PD_WAIT(CMU, 0x0118, PLL_CON_LOCKED, PLL_CON_LOCKED),	/* PLL_CON6_PLL_AUR */
	PD_SAVE(CMU, 0x1800),	/* CLK_CON_DIV_CLK_AUR_ADD_CH_CLK */
	PD_SAVE(CMU, 0x1804),	/* CLK_CON_DIV_DIV_CLK_AUR_AUR */
	PD_SAVE(CMU, 0x1808),	/* CLK_CON_DIV_DIV_CLK_AUR_AURCTL_LH */
	PD_SAVE(CMU, 0x180c),	/* CLK_CON_DIV_DIV_CLK_AUR_NOCP */
	PD_SAVE(CMU, 0x1810),	/* CLK_CON_DIV_DIV_CLK_AUR_NOCP_LH */
	PD_SAVE(CMU, 0x1000),	/* CLK_CON_MUX_MUX_CLK_AUR_AUR */
	PD_SAVE(CMU, 0x0600),	/* PLL_CON0_MUX_CLKCMU_AUR_AURCTL_USER */
	PD_SAVE(CMU, 0x0610),	/* PLL_CON0_MUX_CLKCMU_AUR_NOC_USER */
	PD_SAVE(CMU, 0x0620),	/* PLL_CON0_MUX_CLKCMU_AUR_SWITCH_USER */
	PD_SAVE(CMU, 0x010c),	/* PLL_CON3_PLL_AUR */
	PD_SKIP_IF(CMU, 0x010c, PLL_CON_ENABLE, 0),	/* PLL_CON3_PLL_AUR */
	PD_WAIT(CMU, 0x010c, PLL_CON_LOCKED, PLL_CON_LOCKED),	/* PLL_CON3_PLL_AUR */
	PD_SAVE(CMU, 0x0100),	/* PLL_CON0_PLL_AUR */
	PD_SAVE(CMU, 0x0104),	/* PLL_CON1_PLL_AUR */
	PD_SAVE(CMU, 0x3000),	/* DMYQCH_CON_ADD_AUR_QCH */
	PD_SAVE(CMU, 0x3004),	/* DMYQCH_CON_AUR_QCH */
	PD_SAVE(CMU, 0x3038),	/* QCH_CON_ADD_APBIF_AUR_QCH */
	PD_SAVE(CMU, 0x303c),	/* QCH_CON_AUR_CMU_AUR_QCH */
	PD_SAVE(CMU, 0x3040),	/* QCH_CON_BAAW_AUR_QCH */
	PD_SAVE(CMU, 0x3044),	/* QCH_CON_D_TZPC_AUR_QCH */
	PD_SAVE(CMU, 0x3048),	/* QCH_CON_GPC_AUR_QCH */
	PD_SAVE(CMU, 0x304c),	/* QCH_CON_LH_ACEL_SI_D0_AUR_QCH */
	PD_SAVE(CMU, 0x3050),	/* QCH_CON_LH_ACEL_SI_D1_AUR_QCH */
	PD_SAVE(CMU, 0x3054),	/* QCH_CON_LH_ATB_MI_LT_AUR_CPUCL0_CD_QCH */
	PD_SAVE(CMU, 0x3058),	/* QCH_CON_LH_ATB_SI_LT_AUR_CPUCL0_CD_QCH */
	PD_SAVE(CMU, 0x305c),	/* QCH_CON_LH_ATB_SI_LT_AUR_CPUCL0_QCH */
	PD_SAVE(CMU, 0x3064),	/* QCH_CON_LH_AXI_MI_P_AUR_CU_QCH */
	PD_SAVE(CMU, 0x3070),	/* QCH_CON_LH_AXI_SI_P_AUR_CU_QCH */
	PD_SAVE(CMU, 0x3074),	/* QCH_CON_PPMU_D0_AUR_QCH */
	PD_SAVE(CMU, 0x3078),	/* QCH_CON_PPMU_D1_AUR_QCH */
	PD_SAVE(CMU, 0x3080),	/* QCH_CON_SLH_AXI_MI_P_AUR_QCH */
	PD_SAVE(CMU, 0x3084),	/* QCH_CON_SSMT_D0_AUR_QCH */
	PD_SAVE(CMU, 0x3088),	/* QCH_CON_SSMT_D1_AUR_QCH */
	PD_SAVE(CMU, 0x308c),	/* QCH_CON_SSMT_P_AUR_QCH */
	PD_SAVE(CMU, 0x3090),	/* QCH_CON_SYSMMU_S0_AUR_QCH_S0 */
	PD_SAVE(CMU, 0x3094),	/* QCH_CON_SYSMMU_S0_PMMU0_AUR_QCH_S0 */
	PD_SAVE(CMU, 0x3098),	/* QCH_CON_SYSMMU_S0_PMMU1_AUR_QCH_S0 */
	PD_SAVE(CMU, 0x309c),	/* QCH_CON_SYSREG_AUR_QCH */
	PD_SAVE(CMU, 0x30a0),	/* QCH_CON_UASC_P0_AUR_QCH */
	PD_SAVE(CMU, 0x30a4),	/* QCH_CON_UASC_P1_AUR_QCH */
	PD_SAVE(CMU, 0x0800),	/* AUR_CMU_AUR_CONTROLLER_OPTION */
	PD_SAVE(CMU, 0x0820),	/* AUR_SHORTSTOP */
	PD_SAVE(CMU, 0x0834),	/* AUR_CLKDIVSTEP_CON */
	PD_SAVE(CMU, 0x0830),	/* AUR_CLKDIVSTEP */
	PD_SAVE(SYSREG, 0x0104),	/* BUS_COMPONENT_DRCG_EN */
	PD_SAVE(SYSREG, 0x0108),	/* MEMCLK */
};

/* BW */
static const struct exynos_pd_step zumapro_bw_save[] = {
	PD_SAVE(CMU, 0x1800),	/* CLK_CON_DIV_DIV_CLK_BW_NOCP */
	PD_SAVE(CMU, 0x0600),	/* PLL_CON0_MUX_CLKCMU_BW_NOC_USER */
	PD_SAVE(CMU, 0x3000),	/* DMYQCH_CON_BW_QCH */
	PD_SAVE(CMU, 0x3014),	/* QCH_CON_BW_CMU_BW_QCH */
	PD_SAVE(CMU, 0x3018),	/* QCH_CON_D_TZPC_BW_QCH */
	PD_SAVE(CMU, 0x301c),	/* QCH_CON_GPC_BW_QCH */
	PD_SAVE(CMU, 0x3020),	/* QCH_CON_LH_AXI_MI_IP_BW_QCH */
	PD_SAVE(CMU, 0x3024),	/* QCH_CON_LH_AXI_SI_D_BW_QCH */
	PD_SAVE(CMU, 0x3028),	/* QCH_CON_LH_AXI_SI_IP_BW_QCH */
	PD_SAVE(CMU, 0x302c),	/* QCH_CON_PPMU_BW_QCH */
	PD_SAVE(CMU, 0x3030),	/* QCH_CON_SLH_AXI_MI_P_BW_QCH */
	PD_SAVE(CMU, 0x3034),	/* QCH_CON_SSMT_BW_QCH */
	PD_SAVE(CMU, 0x3038),	/* QCH_CON_SYSMMU_S0_BW_QCH */
	PD_SAVE(CMU, 0x303c),	/* QCH_CON_SYSMMU_S0_PMMU0_BW_QCH */
	PD_SAVE(CMU, 0x3040),	/* QCH_CON_SYSREG_BW_QCH */
	PD_SAVE(CMU, 0x3044),	/* QCH_CON_TREX_D_BW_QCH */
	PD_SAVE(CMU, 0x3048),	/* QCH_CON_UASC_BW_QCH */
	PD_SAVE(CMU, 0x0800),	/* BW_CMU_BW_CONTROLLER_OPTION */
	PD_SAVE(SYSREG, 0x0104),	/* BUS_COMPONENT_DRCG_EN */
	PD_SAVE(SYSREG, 0x0108),	/* MEMCLK */
};

/* EH */
static const struct exynos_pd_step zumapro_eh_save[] = {
	PD_SAVE(CMU, 0x1800),	/* CLK_CON_DIV_DIV_CLK_EH_NOCP */
	PD_SAVE(CMU, 0x1804),	/* CLK_CON_DIV_DIV_CLK_EH_NOCP_LH */
	PD_SAVE(CMU, 0x0600),	/* PLL_CON0_MUX_CLKCMU_EH_NOC_USER */
	PD_SAVE(CMU, 0x3018),	/* QCH_CON_D_TZPC_EH_QCH */
	PD_SAVE(CMU, 0x301c),	/* QCH_CON_EH_CMU_EH_QCH */
	PD_SAVE(CMU, 0x3020),	/* QCH_CON_EH_QCH */
	PD_SAVE(CMU, 0x3024),	/* QCH_CON_GPC_EH_QCH */
	PD_SAVE(CMU, 0x3028),	/* QCH_CON_LH_ACEL_SI_LD_EH_CPUCL0_QCH */
	PD_SAVE(CMU, 0x302c),	/* QCH_CON_LH_AXI_MI_IP_EH_QCH */
	PD_SAVE(CMU, 0x3030),	/* QCH_CON_LH_AXI_MI_P_EH_CU_QCH */
	PD_SAVE(CMU, 0x3034),	/* QCH_CON_LH_AXI_SI_IP_EH_QCH */
	PD_SAVE(CMU, 0x3038),	/* QCH_CON_LH_AXI_SI_P_EH_CU_QCH */
	PD_SAVE(CMU, 0x303c),	/* QCH_CON_PPC_EH_CYCLE_QCH */
	PD_SAVE(CMU, 0x3040),	/* QCH_CON_PPC_EH_EVENT_QCH */
	PD_SAVE(CMU, 0x3044),	/* QCH_CON_PPMU_EH_QCH */
	PD_SAVE(CMU, 0x3048),	/* QCH_CON_QE_EH_QCH */
	PD_SAVE(CMU, 0x304c),	/* QCH_CON_SLH_AXI_MI_P_EH_QCH */
	PD_SAVE(CMU, 0x3050),	/* QCH_CON_SSMT_EH_QCH */
	PD_SAVE(CMU, 0x3054),	/* QCH_CON_SYSMMU_S0_EH_QCH */
	PD_SAVE(CMU, 0x3058),	/* QCH_CON_SYSMMU_S0_PMMU0_EH_QCH */
	PD_SAVE(CMU, 0x305c),	/* QCH_CON_SYSREG_EH_QCH */
	PD_SAVE(CMU, 0x3060),	/* QCH_CON_UASC_EH_QCH */
	PD_SAVE(CMU, 0x0800),	/* EH_CMU_EH_CONTROLLER_OPTION */
	PD_SAVE(SYSREG, 0x0104),	/* BUS_COMPONENT_DRCG_EN */
	PD_SAVE(SYSREG, 0x0108),	/* MEMCLK */
};

/* ISPFE */
static const struct exynos_pd_step zumapro_ispfe_save[] = {
	PD_SAVE(CMU, 0x1800),	/* CLK_CON_DIV_DIV_CLK_ISPFE_DCPHY */
	PD_SAVE(CMU, 0x1804),	/* CLK_CON_DIV_DIV_CLK_ISPFE_NOCP */
	PD_SAVE(CMU, 0x0600),	/* PLL_CON0_MUX_CLKCMU_ISPFE_NOC_USER */
	PD_SAVE(CMU, 0x301c),	/* QCH_CON_BAAW_ISPFE_QCH */
	PD_SAVE(CMU, 0x3020),	/* QCH_CON_D_TZPC_ISPFE_QCH */
	PD_SAVE(CMU, 0x3024),	/* QCH_CON_GPC_ISPFE_QCH */
	PD_SAVE(CMU, 0x3028),	/* QCH_CON_ISPFE_CMU_ISPFE_QCH */
	PD_SAVE(CMU, 0x302c),	/* QCH_CON_ISPFE_QCH_ISPFE */
	PD_SAVE(CMU, 0x3030),	/* QCH_CON_LH_AXI_MI_IP_ISPFE_QCH */
	PD_SAVE(CMU, 0x3034),	/* QCH_CON_LH_AXI_SI_D0_ISPFE_QCH */
	PD_SAVE(CMU, 0x3038),	/* QCH_CON_LH_AXI_SI_D1_ISPFE_QCH */
	PD_SAVE(CMU, 0x303c),	/* QCH_CON_LH_AXI_SI_D2_ISPFE_QCH */
	PD_SAVE(CMU, 0x3040),	/* QCH_CON_LH_AXI_SI_D3_ISPFE_QCH */
	PD_SAVE(CMU, 0x3044),	/* QCH_CON_LH_AXI_SI_IP_ISPFE_QCH */
	PD_SAVE(CMU, 0x3048),	/* QCH_CON_MIPI_PHY_LINK_WRAP_QCH_CSIS0 */
	PD_SAVE(CMU, 0x304c),	/* QCH_CON_MIPI_PHY_LINK_WRAP_QCH_CSIS1 */
	PD_SAVE(CMU, 0x3050),	/* QCH_CON_MIPI_PHY_LINK_WRAP_QCH_CSIS10 */
	PD_SAVE(CMU, 0x3054),	/* QCH_CON_MIPI_PHY_LINK_WRAP_QCH_CSIS11 */
	PD_SAVE(CMU, 0x3058),	/* QCH_CON_MIPI_PHY_LINK_WRAP_QCH_CSIS2 */
	PD_SAVE(CMU, 0x305c),	/* QCH_CON_MIPI_PHY_LINK_WRAP_QCH_CSIS3 */
	PD_SAVE(CMU, 0x3060),	/* QCH_CON_MIPI_PHY_LINK_WRAP_QCH_CSIS4 */
	PD_SAVE(CMU, 0x3064),	/* QCH_CON_MIPI_PHY_LINK_WRAP_QCH_CSIS5 */
	PD_SAVE(CMU, 0x3068),	/* QCH_CON_MIPI_PHY_LINK_WRAP_QCH_CSIS6 */
	PD_SAVE(CMU, 0x306c),	/* QCH_CON_MIPI_PHY_LINK_WRAP_QCH_CSIS7 */
	PD_SAVE(CMU, 0x3070),	/* QCH_CON_MIPI_PHY_LINK_WRAP_QCH_CSIS8 */
	PD_SAVE(CMU, 0x3074),	/* QCH_CON_MIPI_PHY_LINK_WRAP_QCH_CSIS9 */
	PD_SAVE(CMU, 0x3078),	/* QCH_CON_PPMU_D0_ISPFE_QCH */
	PD_SAVE(CMU, 0x307c),	/* QCH_CON_PPMU_D1_ISPFE_QCH */
	PD_SAVE(CMU, 0x3080),	/* QCH_CON_PPMU_D2_ISPFE_QCH */
	PD_SAVE(CMU, 0x3084),	/* QCH_CON_PPMU_D3_ISPFE_QCH */
	PD_SAVE(CMU, 0x3088),	/* QCH_CON_QE_D0_ISPFE_QCH */
	PD_SAVE(CMU, 0x308c),	/* QCH_CON_QE_D1_ISPFE_QCH */
	PD_SAVE(CMU, 0x3090),	/* QCH_CON_QE_D2_ISPFE_QCH */
	PD_SAVE(CMU, 0x3094),	/* QCH_CON_QE_D3_ISPFE_QCH */
	PD_SAVE(CMU, 0x3098),	/* QCH_CON_SLH_AXI_MI_P_ISPFE_QCH */
	PD_SAVE(CMU, 0x309c),	/* QCH_CON_SSMT_D0_ISPFE_QCH */
	PD_SAVE(CMU, 0x30a0),	/* QCH_CON_SSMT_D1_ISPFE_QCH */
	PD_SAVE(CMU, 0x30a4),	/* QCH_CON_SSMT_D2_ISPFE_QCH */
	PD_SAVE(CMU, 0x30a8),	/* QCH_CON_SSMT_D3_ISPFE_QCH */
	PD_SAVE(CMU, 0x30ac),	/* QCH_CON_SYSMMU_S0_ISPFE_QCH_S0 */
	PD_SAVE(CMU, 0x30b0),	/* QCH_CON_SYSMMU_S0_PMMU0_ISPFE_QCH_S0 */
	PD_SAVE(CMU, 0x30b4),	/* QCH_CON_SYSMMU_S0_PMMU1_ISPFE_QCH_S0 */
	PD_SAVE(CMU, 0x30b8),	/* QCH_CON_SYSMMU_S1_ISPFE_QCH_S0 */
	PD_SAVE(CMU, 0x30bc),	/* QCH_CON_SYSMMU_S1_PMMU0_ISPFE_QCH_S0 */
	PD_SAVE(CMU, 0x30c0),	/* QCH_CON_SYSMMU_S2_ISPFE_QCH_S0 */
	PD_SAVE(CMU, 0x30c4),	/* QCH_CON_SYSMMU_S2_PMMU0_ISPFE_QCH_S0 */
	PD_SAVE(CMU, 0x30cc),	/* QCH_CON_SYSREG_ISPFE_QCH */
	PD_SAVE(CMU, 0x30d0),	/* QCH_CON_UASC_ISPFE_QCH */
	PD_SAVE(CMU, 0x0800),	/* ISPFE_CMU_ISPFE_CONTROLLER_OPTION */
	PD_SAVE(SYSREG, 0x0104),	/* BUS_COMPONENT_DRCG_EN */
	PD_SAVE(SYSREG, 0x0108),	/* MEMCLK */
};

/* TPU */
static const struct exynos_pd_step zumapro_tpu_save[] = {
	PD_SAVE(CMU, 0x0000),	/* PLL_LOCKTIME_PLL_TPU */
	PD_SAVE(CMU, 0x0080),	/* PLL_LOCKTIME_REG_PLL_TPU */
	PD_SAVE(CMU, 0x0108),	/* PLL_CON2_PLL_TPU */
	PD_SAVE(CMU, 0x0110),	/* PLL_CON4_PLL_TPU */
	PD_SAVE(CMU, 0x0114),	/* PLL_CON5_PLL_TPU */
	PD_SAVE(CMU, 0x0118),	/* PLL_CON6_PLL_TPU */
	PD_SAVE(CMU, 0x011c),	/* PLL_CON7_PLL_TPU */
	PD_SAVE(CMU, 0x0120),	/* PLL_CON8_PLL_TPU */
	PD_SAVE(CMU, 0x010c),	/* PLL_CON3_PLL_TPU */
	PD_SAVE(CMU, 0x1800),	/* CLK_CON_DIV_CLK_TPU_ADD_CH_CLK */
	PD_SAVE(CMU, 0x1804),	/* CLK_CON_DIV_DIV_CLK_TPU_NOCP */
	PD_SAVE(CMU, 0x1808),	/* CLK_CON_DIV_DIV_CLK_TPU_NOCP_LH */
	PD_SAVE(CMU, 0x180c),	/* CLK_CON_DIV_DIV_CLK_TPU_TPU */
	PD_SAVE(CMU, 0x1810),	/* CLK_CON_DIV_DIV_CLK_TPU_TPUCTL */
	PD_SAVE(CMU, 0x1814),	/* CLK_CON_DIV_DIV_CLK_TPU_TPUCTL_DBG */
	PD_SAVE(CMU, 0x1000),	/* CLK_CON_MUX_MUX_CLK_TPU_NOC_LPM */
	PD_SAVE(CMU, 0x1004),	/* CLK_CON_MUX_MUX_CLK_TPU_TPU */
	PD_SAVE(CMU, 0x1008),	/* CLK_CON_MUX_MUX_CLK_TPU_TPUCTL */
	PD_SAVE(CMU, 0x100c),	/* CLK_CON_MUX_MUX_CLK_TPU_TPUCTRL_LPM */
	PD_SAVE(CMU, 0x1010),	/* CLK_CON_MUX_MUX_CLK_TPU_TPU_LPM */
	PD_SAVE(CMU, 0x0600),	/* PLL_CON0_MUX_CLKCMU_TPU_NOC_USER */
	PD_SAVE(CMU, 0x0610),	/* PLL_CON0_MUX_CLKCMU_TPU_TPUCTL_USER */
	PD_SAVE(CMU, 0x0620),	/* PLL_CON0_MUX_CLKCMU_TPU_TPU_USER */
	PD_SKIP_IF(CMU, 0x010c, PLL_CON_ENABLE, 0),	/* PLL_CON3_PLL_TPU */
	PD_WAIT(CMU, 0x010c, PLL_CON_LOCKED, PLL_CON_LOCKED),	/* PLL_CON3_PLL_TPU */
	PD_SAVE(CMU, 0x0100),	/* PLL_CON0_PLL_TPU */
	PD_SAVE(CMU, 0x0104),	/* PLL_CON1_PLL_TPU */
	PD_SAVE(CMU, 0x3000),	/* DMYQCH_CON_ADD_TPU_QCH */
	PD_SAVE(CMU, 0x3004),	/* DMYQCH_CON_TPU_QCH */
	PD_SAVE(CMU, 0x3040),	/* QCH_CON_ADD_APBIF_TPU_QCH */
	PD_SAVE(CMU, 0x3044),	/* QCH_CON_D_TZPC_TPU_QCH */
	PD_SAVE(CMU, 0x3048),	/* QCH_CON_GPC_TPU_QCH */
	PD_SAVE(CMU, 0x304c),	/* QCH_CON_LH_ACEL_SI_D0_TPU_QCH */
	PD_SAVE(CMU, 0x3050),	/* QCH_CON_LH_ACEL_SI_D1_TPU_QCH */
	PD_SAVE(CMU, 0x3054),	/* QCH_CON_LH_ATB_MI_LT0_TPU_CPUCL0_CD_QCH */
	PD_SAVE(CMU, 0x3058),	/* QCH_CON_LH_ATB_MI_LT1_TPU_CPUCL0_CD_QCH */
	PD_SAVE(CMU, 0x305c),	/* QCH_CON_LH_ATB_SI_LT0_TPU_CPUCL0_CD_QCH */
	PD_SAVE(CMU, 0x3060),	/* QCH_CON_LH_ATB_SI_LT0_TPU_CPUCL0_QCH */
	PD_SAVE(CMU, 0x3064),	/* QCH_CON_LH_ATB_SI_LT1_TPU_CPUCL0_CD_QCH */
	PD_SAVE(CMU, 0x3068),	/* QCH_CON_LH_ATB_SI_LT1_TPU_CPUCL0_QCH */
	PD_SAVE(CMU, 0x3070),	/* QCH_CON_LH_AXI_MI_P_TPU_CU_QCH */
	PD_SAVE(CMU, 0x3078),	/* QCH_CON_LH_AXI_SI_P_TPU_CU_QCH */
	PD_SAVE(CMU, 0x307c),	/* QCH_CON_PPMU_D0_TPU_QCH */
	PD_SAVE(CMU, 0x3080),	/* QCH_CON_PPMU_D1_TPU_QCH */
	PD_SAVE(CMU, 0x3088),	/* QCH_CON_SLH_AXI_MI_P_TPU_QCH */
	PD_SAVE(CMU, 0x308c),	/* QCH_CON_SSMT_D0_TPU_QCH */
	PD_SAVE(CMU, 0x3090),	/* QCH_CON_SSMT_D1_TPU_QCH */
	PD_SAVE(CMU, 0x3094),	/* QCH_CON_SYSMMU_S0_PMMU0_TPU_QCH */
	PD_SAVE(CMU, 0x3098),	/* QCH_CON_SYSMMU_S0_PMMU1_TPU_QCH */
	PD_SAVE(CMU, 0x309c),	/* QCH_CON_SYSMMU_S0_TPU_QCH */
	PD_SAVE(CMU, 0x30a0),	/* QCH_CON_SYSREG_TPU_QCH */
	PD_SAVE(CMU, 0x30a4),	/* QCH_CON_TPU_CMU_TPU_QCH */
	PD_SAVE(CMU, 0x0800),	/* TPU_CMU_TPU_CONTROLLER_OPTION */
	PD_SAVE(CMU, 0x0840),	/* TPU_CLKDIVSTEP_CON_HEAVY */
	PD_SAVE(CMU, 0x0844),	/* TPU_CLKDIVSTEP_CON_LIGHT */
	PD_SAVE(CMU, 0x0834),	/* TPU_CLKDIVSTEP_OCP_FLT */
	PD_SAVE(CMU, 0x0838),	/* TPU_CLKDIVSTEP_VDROOP_FLT */
	PD_SAVE(CMU, 0x083c),	/* TPU_CLKDIVSTEP_SMPL_FLT */
	PD_SAVE(CMU, 0x0830),	/* TPU_CLKDIVSTEP */
	PD_SAVE(CMU, 0x0820),	/* TPU_SHORTSTOP */
	PD_SAVE(CMU, 0x0860),	/* TPU_HCHGEN_CLKMUX_LPM */
	PD_SAVE(SYSREG, 0x0104),	/* BUS_COMPONENT_DRCG_EN */
	PD_SAVE(SYSREG, 0x0108),	/* MEMCLK */
};

/* HSI0 */
static const struct exynos_pd_step zumapro_hsi0_save[] = {
	PD_SAVE(CMU, 0x0000),	/* PLL_LOCKTIME_PLL_USB */
	PD_SAVE(CMU, 0x0080),	/* PLL_LOCKTIME_REG_PLL_USB */
	PD_SAVE(CMU, 0x0108),	/* PLL_CON2_PLL_USB */
	PD_SAVE(CMU, 0x0110),	/* PLL_CON4_PLL_USB */
	PD_SAVE(CMU, 0x0114),	/* PLL_CON5_PLL_USB */
	PD_SAVE(CMU, 0x0118),	/* PLL_CON6_PLL_USB */
	PD_SAVE(CMU, 0x011c),	/* PLL_CON7_PLL_USB */
	PD_SAVE(CMU, 0x0120),	/* PLL_CON8_PLL_USB */
	PD_SAVE(CMU, 0x010c),	/* PLL_CON3_PLL_USB */
	PD_SAVE(CMU, 0x1800),	/* CLK_CON_DIV_DIV_CLK_HSI0_NOC_LH */
	PD_SAVE(CMU, 0x1804),	/* CLK_CON_DIV_DIV_CLK_HSI0_USB */
	PD_SAVE(CMU, 0x1808),	/* CLK_CON_DIV_DIV_CLK_HSI0_USB32DRD */
	PD_SAVE(CMU, 0x180c),	/* CLK_CON_DIV_DIV_CLK_HSI0_EUSB */
	PD_SAVE(CMU, 0x1810),	/* CLK_CON_DIV_DIV_CLK_HSI0_I3C */
	PD_SAVE(CMU, 0x1814),	/* CLK_CON_DIV_DIV_CLK_HSI0_USI0 */
	PD_SAVE(CMU, 0x1818),	/* CLK_CON_DIV_DIV_CLK_HSI0_USI1 */
	PD_SAVE(CMU, 0x181c),	/* CLK_CON_DIV_DIV_CLK_HSI0_USI2 */
	PD_SAVE(CMU, 0x1820),	/* CLK_CON_DIV_DIV_CLK_HSI0_USI3 */
	PD_SAVE(CMU, 0x1824),	/* CLK_CON_DIV_DIV_CLK_HSI0_USI4 */
	PD_SAVE(CMU, 0x1000),	/* CLK_CON_MUX_MUX_CLK_HSI0_NOC */
	PD_SAVE(CMU, 0x1004),	/* CLK_CON_MUX_MUX_CLK_HSI0_USB20_REF */
	PD_SAVE(CMU, 0x1008),	/* CLK_CON_MUX_MUX_CLK_HSI0_USB32DRD */
	PD_SAVE(CMU, 0x100c),	/* CLK_CON_MUX_MUX_CLK_HSI0_I3C */
	PD_SAVE(CMU, 0x1010),	/* CLK_CON_MUX_MUX_CLK_HSI0_RTCCLK */
	PD_SAVE(CMU, 0x1014),	/* CLK_CON_MUX_MUX_CLK_HSI0_USI0 */
	PD_SAVE(CMU, 0x1018),	/* CLK_CON_MUX_MUX_CLK_HSI0_USI1 */
	PD_SAVE(CMU, 0x101c),	/* CLK_CON_MUX_MUX_CLK_HSI0_USI2 */
	PD_SAVE(CMU, 0x1020),	/* CLK_CON_MUX_MUX_CLK_HSI0_USI3 */
	PD_SAVE(CMU, 0x1024),	/* CLK_CON_MUX_MUX_CLK_HSI0_USI4 */
	PD_SAVE(CMU, 0x0600),	/* PLL_CON0_MUX_CLKCMU_HSI0_ALT_USER */
	PD_SAVE(CMU, 0x0610),	/* PLL_CON0_MUX_CLKCMU_HSI0_DPGTC_USER */
	PD_SAVE(CMU, 0x0620),	/* PLL_CON0_MUX_CLKCMU_HSI0_NOC_USER */
	PD_SAVE(CMU, 0x0630),	/* PLL_CON0_MUX_CLKCMU_HSI0_TCXO_USER */
	PD_SAVE(CMU, 0x0640),	/* PLL_CON0_MUX_CLKCMU_HSI0_USB20_USER */
	PD_SAVE(CMU, 0x0650),	/* PLL_CON0_MUX_CLKCMU_HSI0_USB32DRD_USER */
	PD_SAVE(CMU, 0x0660),	/* PLL_CON0_MUX_CLKCMU_HSI0_USPDPDBG_USER */
	PD_SAVE(CMU, 0x0670),	/* PLL_CON0_MUX_CLKCMU_HSI0_DPOSC_USER */
	PD_SAVE(CMU, 0x0680),	/* PLL_CON0_MUX_CLKCMU_HSI0_PERI_USER */
	PD_SKIP_IF(CMU, 0x010c, PLL_CON_ENABLE, 0),	/* PLL_CON3_PLL_USB */
	PD_WAIT(CMU, 0x010c, PLL_CON_LOCKED, PLL_CON_LOCKED),	/* PLL_CON3_PLL_USB */
	PD_SAVE(CMU, 0x0100),	/* PLL_CON0_PLL_USB */
	PD_SAVE(CMU, 0x0104),	/* PLL_CON1_PLL_USB */
	PD_SAVE(CMU, 0x3000),	/* DMYQCH_CON_USB32DRD_QCH_REF */
	PD_SAVE(CMU, 0x3004),	/* DMYQCH_CON_I3C2_HSI0_QCH_SCLK */
	PD_SAVE(CMU, 0x3038),	/* QCH_CON_DP_LINK_QCH_GTC_CLK */
	PD_SAVE(CMU, 0x303c),	/* QCH_CON_DP_LINK_QCH_PCLK */
	PD_SAVE(CMU, 0x3040),	/* QCH_CON_D_TZPC_HSI0_QCH */
	PD_SAVE(CMU, 0x3044),	/* QCH_CON_ETR_MIU_QCH_ACLK */
	PD_SAVE(CMU, 0x3048),	/* QCH_CON_ETR_MIU_QCH_PCLK */
	PD_SAVE(CMU, 0x304c),	/* QCH_CON_GPC_HSI0_QCH */
	PD_SAVE(CMU, 0x3050),	/* QCH_CON_HSI0_CMU_HSI0_QCH */
	PD_SAVE(CMU, 0x3054),	/* QCH_CON_LH_ACEL_SI_D_HSI0_QCH */
	PD_SAVE(CMU, 0x305c),	/* QCH_CON_LH_AXI_MI_LG_ETR_HSI0_CU_QCH */
	PD_SAVE(CMU, 0x3060),	/* QCH_CON_LH_AXI_MI_LP_AOC_HSI0_CU_QCH */
	PD_SAVE(CMU, 0x3064),	/* QCH_CON_LH_AXI_MI_P_HSI0_CU_QCH */
	PD_SAVE(CMU, 0x3068),	/* QCH_CON_LH_AXI_SI_LD_HSI0_AOC_QCH */
	PD_SAVE(CMU, 0x306c),	/* QCH_CON_LH_AXI_SI_LG_ETR_HSI0_CU_QCH */
	PD_SAVE(CMU, 0x3070),	/* QCH_CON_LH_AXI_SI_LP_AOC_HSI0_CU_QCH */
	PD_SAVE(CMU, 0x3074),	/* QCH_CON_LH_AXI_SI_P_HSI0_CU_QCH */
	PD_SAVE(CMU, 0x3078),	/* QCH_CON_PPMU_HSI0_QCH */
	PD_SAVE(CMU, 0x307c),	/* DMYQCH_CON_I3C3_HSI0_QCH_SCLK */
	PD_SAVE(CMU, 0x3080),	/* QCH_CON_SLH_AXI_MI_LG_ETR_HSI0_QCH */
	PD_SAVE(CMU, 0x3084),	/* QCH_CON_SLH_AXI_MI_LP_AOC_HSI0_QCH */
	PD_SAVE(CMU, 0x3088),	/* QCH_CON_SLH_AXI_MI_P_HSI0_QCH */
	PD_SAVE(CMU, 0x308c),	/* QCH_CON_SSMT_HSI0_QCH */
	PD_SAVE(CMU, 0x3090),	/* QCH_CON_SYSMMU_S0_HSI0_QCH_S0 */
	PD_SAVE(CMU, 0x3094),	/* QCH_CON_DP_LINK_QCH_OSC_CLK */
	PD_SAVE(CMU, 0x3098),	/* QCH_CON_SYSMMU_S0_PMMU0_HSI0_QCH_S0 */
	PD_SAVE(CMU, 0x309c),	/* QCH_CON_I3C2_HSI0_QCH_PCLK */
	PD_SAVE(CMU, 0x30a0),	/* QCH_CON_I3C3_HSI0_QCH_PCLK */
	PD_SAVE(CMU, 0x30a4),	/* QCH_CON_SYSREG_HSI0_QCH */
	PD_SAVE(CMU, 0x30a8),	/* QCH_CON_USB32DRD_QCH_EUSBPHY */
	PD_SAVE(CMU, 0x30ac),	/* QCH_CON_UASC_HSI0_LINK_QCH */
	PD_SAVE(CMU, 0x30b0),	/* QCH_CON_USB32DRD_QCH_USBDPPHY_CTRL */
	PD_SAVE(CMU, 0x30b4),	/* QCH_CON_USB32DRD_QCH_USBDPPHY_TCA */
	PD_SAVE(CMU, 0x30b8),	/* QCH_CON_USB32DRD_QCH_EUSBCTL */
	PD_SAVE(CMU, 0x30bc),	/* QCH_CON_USB32DRD_QCH_SUBCTL */
	PD_SAVE(CMU, 0x30c0),	/* QCH_CON_USB32DRD_QCH_LINK */
	PD_SAVE(CMU, 0x30c4),	/* QCH_CON_USI0_HSI0_QCH */
	PD_SAVE(CMU, 0x30c8),	/* QCH_CON_USI1_HSI0_QCH */
	PD_SAVE(CMU, 0x30cc),	/* QCH_CON_USI2_HSI0_QCH */
	PD_SAVE(CMU, 0x30d0),	/* QCH_CON_USI3_HSI0_QCH */
	PD_SAVE(CMU, 0x30d4),	/* QCH_CON_USI4_HSI0_QCH */
	PD_SAVE(CMU, 0x0800),	/* HSI0_CMU_HSI0_CONTROLLER_OPTION */
	PD_SAVE(SYSREG, 0x0104),	/* BUS_COMPONENT_DRCG_EN */
	PD_SAVE(SYSREG, 0x0108),	/* MEMCLK */
};

const struct exynos_pd_sequences zumapro_pd_sequences[] = {
	/* G3D */
	EXYNOS_PD_SEQUENCES(0x15461a80, zumapro_pd_on, zumapro_g3d_save,
			    zumapro_pd_off),
	/* EMBEDDED_G3D */
	EXYNOS_PD_SEQUENCES_NO_SAVE(0x15461c80, zumapro_g3d_cores_on,
				    zumapro_g3d_cores_off),
	/* DPUB */
	EXYNOS_PD_SEQUENCES(0x15461d00, zumapro_pd_on, zumapro_dpub_save,
			    zumapro_pd_off),
	/* DPUF0 */
	EXYNOS_PD_SEQUENCES(0x15461d80, zumapro_pd_on, zumapro_dpuf0_save,
			    zumapro_pd_off),
	/* DPUF1 */
	EXYNOS_PD_SEQUENCES(0x15461e00, zumapro_pd_on, zumapro_dpuf1_save,
			    zumapro_pd_off),
	/* MFC */
	EXYNOS_PD_SEQUENCES(0x15462080, zumapro_pd_on, zumapro_mfc_save,
			    zumapro_pd_off),
	/* HSI1 */
	EXYNOS_PD_SEQUENCES(0x15462b00, zumapro_pd_on, zumapro_hsi1_save,
			    zumapro_pd_off),
	/* G2D */
	EXYNOS_PD_SEQUENCES(0x15461e80, zumapro_pd_on, zumapro_g2d_save,
			    zumapro_pd_off),
	/* GDC */
	EXYNOS_PD_SEQUENCES(0x15461f00, zumapro_pd_on, zumapro_gdc_save,
			    zumapro_pd_off),
	/* GSE */
	EXYNOS_PD_SEQUENCES(0x15461f80, zumapro_pd_on, zumapro_gse_save,
			    zumapro_pd_off),
	/* MCSC */
	EXYNOS_PD_SEQUENCES(0x15462000, zumapro_pd_on, zumapro_mcsc_save,
			    zumapro_pd_off),
	/* RGBP */
	EXYNOS_PD_SEQUENCES(0x15462100, zumapro_pd_on, zumapro_rgbp_save,
			    zumapro_pd_off),
	/* TNR */
	EXYNOS_PD_SEQUENCES(0x15462180, zumapro_pd_on, zumapro_tnr_save,
			    zumapro_pd_off),
	/* YUVP */
	EXYNOS_PD_SEQUENCES(0x15462200, zumapro_pd_on, zumapro_yuvp_save,
			    zumapro_pd_off),
	/* AOC */
	EXYNOS_PD_SEQUENCES_NO_SAVE(0x15462280, zumapro_pd_on, zumapro_pd_off),
	/* AUR */
	EXYNOS_PD_SEQUENCES(0x15462300, zumapro_pd_on, zumapro_aur_save,
			    zumapro_pd_off),
	/* BW */
	EXYNOS_PD_SEQUENCES(0x15462380, zumapro_pd_on, zumapro_bw_save,
			    zumapro_pd_off),
	/* EH */
	EXYNOS_PD_SEQUENCES(0x15462400, zumapro_pd_on, zumapro_eh_save,
			    zumapro_pd_off),
	/* ISPFE */
	EXYNOS_PD_SEQUENCES(0x15462480, zumapro_pd_on, zumapro_ispfe_save,
			    zumapro_pd_off),
	/* TPU */
	EXYNOS_PD_SEQUENCES(0x15462500, zumapro_pd_on, zumapro_tpu_save,
			    zumapro_pd_off),
	/* HSI0 */
	EXYNOS_PD_SEQUENCES(0x15462a80, zumapro_pd_on, zumapro_hsi0_save,
			    zumapro_pd_off),
	{ /* sentinel */ },
};
